import { computed } from 'vue'
import { i18n } from '@/i18n'

const messages = {
  en: {
    title: 'Model Plaza',
    subtitle: 'Compare models, visible groups, and channel-specific pricing.',
    searchPlaceholder: 'Search models, providers, groups, or channels',
    allGroups: 'All groups',
    allProviders: 'All providers',
    allBillingModes: 'All billing modes',
    allStatuses: 'All statuses',
    allCapabilities: 'All capabilities',
    reset: 'Reset',
    refresh: 'Refresh',
    results: '{count} models',
    loading: 'Loading model catalog...',
    loadFailed: 'The model catalog could not be loaded.',
    retry: 'Retry',
    empty: 'No models match the current filters.',
    emptyHint: 'Reset filters or try a different search.',
    disabled: 'Model Plaza is not enabled for this site.',
    unavailable: 'Unavailable',
    available: 'Available',
    maintenance: 'Maintenance',
    unknown: 'Unknown',
    details: 'Details',
    copyModel: 'Copy model ID',
    copied: 'Copied',
    groups: 'Groups',
    channels: 'Channels',
    provider: 'Provider',
    contextWindow: 'Context window',
    capabilities: 'Capabilities',
    pricing: 'Pricing',
    noPricing: 'Pricing unavailable',
    priceVariants: '{count} channel-specific prices',
    tokenBilling: 'Token billing',
    requestBilling: 'Per request',
    imageBilling: 'Image billing',
    input: 'Input',
    output: 'Output',
    cacheWrite: 'Cache write',
    cacheRead: 'Cache read',
    imageOutput: 'Image output',
    perRequest: 'Request',
    perMillion: '/ 1M tokens',
    each: '/ request',
    overview: 'Overview',
    performance: 'Performance',
    api: 'API',
    sourceOffers: 'Available offers',
    legacyOffer: 'Catalog pricing',
    normalRate: 'Rate',
    peakRate: 'Peak {start}-{end}',
    intervals: 'Pricing intervals',
    range: 'Range',
    tier: 'Tier',
    currentStatus: 'Current status',
    visibleChannels: 'Visible channels',
    lastUpdated: 'Last updated',
    notReported: 'Not reported',
    performanceUnavailable: 'No model-safe latency measurement is available for this catalog item.',
    performanceHint: 'Only verified catalog status and source availability are shown.',
    apiExample: 'Request example',
    curl: 'cURL',
    openaiSdk: 'OpenAI SDK',
    codex: 'Codex',
    copyCode: 'Copy code',
    streaming: 'Streaming',
    vision: 'Vision',
    tools: 'Tools',
    json: 'JSON',
    exclusive: 'Exclusive',
  },
  zh: {
    title: '模型广场',
    subtitle: '按模型查看可用分组、能力与各渠道独立定价。',
    searchPlaceholder: '搜索模型、供应商、分组或渠道',
    allGroups: '所有分组',
    allProviders: '所有供应商',
    allBillingModes: '所有计费方式',
    allStatuses: '所有状态',
    allCapabilities: '所有能力',
    reset: '重置',
    refresh: '刷新',
    results: '共 {count} 个模型',
    loading: '正在加载模型目录...',
    loadFailed: '模型目录加载失败。',
    retry: '重试',
    empty: '没有符合当前筛选条件的模型。',
    emptyHint: '请重置筛选或更换搜索词。',
    disabled: '当前站点未启用模型广场。',
    unavailable: '不可用',
    available: '可用',
    maintenance: '维护中',
    unknown: '未知',
    details: '详情',
    copyModel: '复制模型 ID',
    copied: '已复制',
    groups: '分组',
    channels: '渠道',
    provider: '供应商',
    contextWindow: '上下文窗口',
    capabilities: '模型能力',
    pricing: '定价',
    noPricing: '暂无定价',
    priceVariants: '{count} 个渠道独立定价',
    tokenBilling: '按 Token 计费',
    requestBilling: '按请求计费',
    imageBilling: '图片计费',
    input: '输入',
    output: '输出',
    cacheWrite: '缓存写入',
    cacheRead: '缓存读取',
    imageOutput: '图片输出',
    perRequest: '单次请求',
    perMillion: '/ 百万 Token',
    each: '/ 次',
    overview: '概览',
    performance: '性能',
    api: 'API',
    sourceOffers: '可用渠道报价',
    legacyOffer: '目录聚合定价',
    normalRate: '倍率',
    peakRate: '峰值 {start}-{end}',
    intervals: '分档价格',
    range: '区间',
    tier: '档位',
    currentStatus: '当前状态',
    visibleChannels: '可见渠道',
    lastUpdated: '更新时间',
    notReported: '未提供',
    performanceUnavailable: '当前目录没有可安全关联到此模型的延迟测量。',
    performanceHint: '这里只显示经过验证的目录状态与来源可用性。',
    apiExample: '调用示例',
    curl: 'cURL',
    openaiSdk: 'OpenAI SDK',
    codex: 'Codex',
    copyCode: '复制代码',
    streaming: '流式',
    vision: '视觉',
    tools: '工具调用',
    json: 'JSON',
    exclusive: '专属',
  },
} as const

export type ModelPlazaTextKey = keyof typeof messages.en

export function useModelPlazaText() {
  const language = computed<'en' | 'zh'>(() =>
    String(i18n.global.locale.value).toLowerCase().startsWith('zh') ? 'zh' : 'en'
  )

  function text(key: ModelPlazaTextKey, params: Record<string, string | number> = {}): string {
    let value: string = messages[language.value][key]
    for (const [name, replacement] of Object.entries(params)) {
      value = value.split(`{${name}}`).join(String(replacement))
    }
    return value
  }

  return { language, text }
}
