-- Refine existing content moderation keyword defaults to reduce false positives.
-- This preserves explicit admin opt-in safety: no email notices and no auto-ban
-- unless the admin turns those switches back on after this migration.
UPDATE settings
SET value = (
        jsonb_set(
            COALESCE(NULLIF(value, ''), '{}')::jsonb
                || jsonb_build_object(
                    'email_on_hit', false,
                    'auto_ban_enabled', false
                ),
            '{blocked_keywords}',
            (
                SELECT COALESCE(jsonb_agg(keyword), '[]'::jsonb)
                FROM jsonb_array_elements_text(
                    COALESCE(
                        COALESCE(NULLIF(value, ''), '{}')::jsonb->'blocked_keywords',
                        '[]'::jsonb
                    )
                ) AS existing(keyword)
                WHERE lower(trim(keyword)) NOT IN (
                    'reverse shell',
                    'bypass waf',
                    'captcha bypass',
                    'password brute force',
                    'credential theft',
                    'unauthorized penetration test',
                    'penetration attack',
                    'detection evasion',
                    'antivirus evasion',
                    'license bypass',
                    'drm bypass',
                    'activation bypass',
                    'mass signup',
                    'account farming',
                    'review bot',
                    'scrape at scale',
                    'anti bot bypass',
                    'anti crawler bypass',
                    'tampermonkey bot',
                    'jailbreak prompt',
                    'jailbreak prompt to bypass',
                    'prompt to bypass content policy',
                    'bypass content policy prompt',
                    'bypass content policy',
                    'bypass risk control',
                    'bypass risk control prompt',
                    'bypass security policy',
                    'bypass security policy prompt',
                    'bypass safety checks',
                    'bypass safety checks prompt',
                    'anti crawler bypass',
                    'anti bot bypass',
                    '反弹shell',
                    '未授权渗透',
                    '渗透攻击',
                    '内网渗透',
                    '批量扫漏洞',
                    '验证码破解',
                    '破解验证码',
                    '绕过验证码',
                    '绕过滑块',
                    '绕过waf',
                    '绕过反爬',
                    '绕过安全检测',
                    '安全策略绕过',
                    '批量注册',
                    '批量养号',
                    '批量抓取',
                    '批量爬取',
                    '批量抓取禁爬',
                    '批量爬取禁爬',
                    '自动刷单',
                    '自动刷量',
                    '自动控评',
                    '人肉搜索',
                    '曝光隐私',
                    '网暴话术',
                    '恶意辱骂',
                    '恐吓短信',
                    '勒索信息',
                    '钓鱼群发',
                    '诈骗群发',
                    '授权绕过',
                    '绕过授权',
                    '激活破解',
                    '破解激活',
                    '脱壳破解',
                    '逆向破解',
                    '越狱绕过',
                    '绕过风控',
                    '绕过内容审计',
                    '绕过内容审计提示词',
                    '越狱提示词',
                    '提示词越狱',
                    '提示词越狱模板',
                    '绕过模型安全',
                    '绕过模型安全提示词',
                    '验证码破解教程',
                    '破解验证码教程',
                    '绕过验证码教程',
                    '绕过waf教程',
                    '绕过反爬教程',
                    '如何破解验证码',
                    '怎么破解验证码',
                    '如何绕过验证码',
                    '怎么绕过验证码',
                    '如何绕过反爬',
                    '怎么绕过反爬',
                    '自动绕过验证码',
                    '爬虫绕过反爬',
                    '爬虫抓取禁爬',
                    '油猴刷',
                    '油猴抢',
                    'app自动化抢',
                    'app自动化绕过',
                    '网页自动化刷',
                    '网页自动化绕过风控',
                    'root检测绕过',
                    '生成越狱提示词',
                    '编写越狱提示词',
                    '绕过风控教程'
                )
            ),
            true
        )
    )::text,
    updated_at = NOW()
WHERE key = 'content_moderation_config';
