// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalorderfulfillment"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ExternalOrderFulfillmentUpdate is the builder for updating ExternalOrderFulfillment entities.
type ExternalOrderFulfillmentUpdate struct {
	config
	hooks    []Hook
	mutation *ExternalOrderFulfillmentMutation
}

// Where appends a list predicates to the ExternalOrderFulfillmentUpdate builder.
func (_u *ExternalOrderFulfillmentUpdate) Where(ps ...predicate.ExternalOrderFulfillment) *ExternalOrderFulfillmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ExternalOrderFulfillmentUpdate) SetPlatform(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillablePlatform(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformOrderID sets the "platform_order_id" field.
func (_u *ExternalOrderFulfillmentUpdate) SetPlatformOrderID(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetPlatformOrderID(v)
	return _u
}

// SetNillablePlatformOrderID sets the "platform_order_id" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillablePlatformOrderID(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetPlatformOrderID(*v)
	}
	return _u
}

// SetBuyerRef sets the "buyer_ref" field.
func (_u *ExternalOrderFulfillmentUpdate) SetBuyerRef(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetBuyerRef(v)
	return _u
}

// SetNillableBuyerRef sets the "buyer_ref" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableBuyerRef(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetBuyerRef(*v)
	}
	return _u
}

// ClearBuyerRef clears the value of the "buyer_ref" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearBuyerRef() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearBuyerRef()
	return _u
}

// SetSkuCode sets the "sku_code" field.
func (_u *ExternalOrderFulfillmentUpdate) SetSkuCode(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetSkuCode(v)
	return _u
}

// SetNillableSkuCode sets the "sku_code" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableSkuCode(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetSkuCode(*v)
	}
	return _u
}

// SetSkuName sets the "sku_name" field.
func (_u *ExternalOrderFulfillmentUpdate) SetSkuName(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetSkuName(v)
	return _u
}

// SetNillableSkuName sets the "sku_name" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableSkuName(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetSkuName(*v)
	}
	return _u
}

// ClearSkuName clears the value of the "sku_name" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearSkuName() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearSkuName()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExternalOrderFulfillmentUpdate) SetAmount(v float64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableAmount(v *float64) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExternalOrderFulfillmentUpdate) AddAmount(v float64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ExternalOrderFulfillmentUpdate) SetCurrency(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableCurrency(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *ExternalOrderFulfillmentUpdate) SetRedeemCodeID(v int64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableRedeemCodeID(v *int64) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *ExternalOrderFulfillmentUpdate) AddRedeemCodeID(v int64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearRedeemCodeID() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetRedeemCode sets the "redeem_code" field.
func (_u *ExternalOrderFulfillmentUpdate) SetRedeemCode(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetRedeemCode(v)
	return _u
}

// SetNillableRedeemCode sets the "redeem_code" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableRedeemCode(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetRedeemCode(*v)
	}
	return _u
}

// ClearRedeemCode clears the value of the "redeem_code" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearRedeemCode() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearRedeemCode()
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *ExternalOrderFulfillmentUpdate) SetRedeemType(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableRedeemType(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetRedeemValue sets the "redeem_value" field.
func (_u *ExternalOrderFulfillmentUpdate) SetRedeemValue(v float64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.ResetRedeemValue()
	_u.mutation.SetRedeemValue(v)
	return _u
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableRedeemValue(v *float64) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetRedeemValue(*v)
	}
	return _u
}

// AddRedeemValue adds value to the "redeem_value" field.
func (_u *ExternalOrderFulfillmentUpdate) AddRedeemValue(v float64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.AddRedeemValue(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ExternalOrderFulfillmentUpdate) SetGroupID(v int64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableGroupID(v *int64) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ExternalOrderFulfillmentUpdate) AddGroupID(v int64) *ExternalOrderFulfillmentUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearGroupID() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *ExternalOrderFulfillmentUpdate) SetValidityDays(v int) *ExternalOrderFulfillmentUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableValidityDays(v *int) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *ExternalOrderFulfillmentUpdate) AddValidityDays(v int) *ExternalOrderFulfillmentUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ExternalOrderFulfillmentUpdate) SetExpiresAt(v time.Time) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableExpiresAt(v *time.Time) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearExpiresAt() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetManualURL sets the "manual_url" field.
func (_u *ExternalOrderFulfillmentUpdate) SetManualURL(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetManualURL(v)
	return _u
}

// SetNillableManualURL sets the "manual_url" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableManualURL(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetManualURL(*v)
	}
	return _u
}

// ClearManualURL clears the value of the "manual_url" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearManualURL() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearManualURL()
	return _u
}

// SetDeliveryMessage sets the "delivery_message" field.
func (_u *ExternalOrderFulfillmentUpdate) SetDeliveryMessage(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetDeliveryMessage(v)
	return _u
}

// SetNillableDeliveryMessage sets the "delivery_message" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableDeliveryMessage(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetDeliveryMessage(*v)
	}
	return _u
}

// ClearDeliveryMessage clears the value of the "delivery_message" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearDeliveryMessage() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearDeliveryMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExternalOrderFulfillmentUpdate) SetStatus(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableStatus(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotifyStatus sets the "notify_status" field.
func (_u *ExternalOrderFulfillmentUpdate) SetNotifyStatus(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetNotifyStatus(v)
	return _u
}

// SetNillableNotifyStatus sets the "notify_status" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableNotifyStatus(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetNotifyStatus(*v)
	}
	return _u
}

// SetFailReason sets the "fail_reason" field.
func (_u *ExternalOrderFulfillmentUpdate) SetFailReason(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetFailReason(v)
	return _u
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableFailReason(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetFailReason(*v)
	}
	return _u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearFailReason() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearFailReason()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *ExternalOrderFulfillmentUpdate) SetOperator(v string) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableOperator(v *string) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// ClearOperator clears the value of the "operator" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearOperator() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearOperator()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *ExternalOrderFulfillmentUpdate) SetDeliveredAt(v time.Time) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableDeliveredAt(v *time.Time) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearDeliveredAt() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *ExternalOrderFulfillmentUpdate) SetNotifiedAt(v time.Time) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdate) SetNillableNotifiedAt(v *time.Time) *ExternalOrderFulfillmentUpdate {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *ExternalOrderFulfillmentUpdate) ClearNotifiedAt() *ExternalOrderFulfillmentUpdate {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExternalOrderFulfillmentUpdate) SetUpdatedAt(v time.Time) *ExternalOrderFulfillmentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExternalOrderFulfillmentMutation object of the builder.
func (_u *ExternalOrderFulfillmentUpdate) Mutation() *ExternalOrderFulfillmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExternalOrderFulfillmentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExternalOrderFulfillmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExternalOrderFulfillmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExternalOrderFulfillmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExternalOrderFulfillmentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := externalorderfulfillment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExternalOrderFulfillmentUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := externalorderfulfillment.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformOrderID(); ok {
		if err := externalorderfulfillment.PlatformOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_order_id", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.platform_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerRef(); ok {
		if err := externalorderfulfillment.BuyerRefValidator(v); err != nil {
			return &ValidationError{Name: "buyer_ref", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.buyer_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkuCode(); ok {
		if err := externalorderfulfillment.SkuCodeValidator(v); err != nil {
			return &ValidationError{Name: "sku_code", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.sku_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkuName(); ok {
		if err := externalorderfulfillment.SkuNameValidator(v); err != nil {
			return &ValidationError{Name: "sku_name", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.sku_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := externalorderfulfillment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemCode(); ok {
		if err := externalorderfulfillment.RedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_code", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.redeem_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := externalorderfulfillment.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.redeem_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := externalorderfulfillment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotifyStatus(); ok {
		if err := externalorderfulfillment.NotifyStatusValidator(v); err != nil {
			return &ValidationError{Name: "notify_status", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.notify_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := externalorderfulfillment.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.operator": %w`, err)}
		}
	}
	return nil
}

func (_u *ExternalOrderFulfillmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(externalorderfulfillment.Table, externalorderfulfillment.Columns, sqlgraph.NewFieldSpec(externalorderfulfillment.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(externalorderfulfillment.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformOrderID(); ok {
		_spec.SetField(externalorderfulfillment.FieldPlatformOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerRef(); ok {
		_spec.SetField(externalorderfulfillment.FieldBuyerRef, field.TypeString, value)
	}
	if _u.mutation.BuyerRefCleared() {
		_spec.ClearField(externalorderfulfillment.FieldBuyerRef, field.TypeString)
	}
	if value, ok := _u.mutation.SkuCode(); ok {
		_spec.SetField(externalorderfulfillment.FieldSkuCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkuName(); ok {
		_spec.SetField(externalorderfulfillment.FieldSkuName, field.TypeString, value)
	}
	if _u.mutation.SkuNameCleared() {
		_spec.ClearField(externalorderfulfillment.FieldSkuName, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(externalorderfulfillment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(externalorderfulfillment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(externalorderfulfillment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodeIDCleared() {
		_spec.ClearField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RedeemCode(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemCode, field.TypeString, value)
	}
	if _u.mutation.RedeemCodeCleared() {
		_spec.ClearField(externalorderfulfillment.FieldRedeemCode, field.TypeString)
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemValue(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRedeemValue(); ok {
		_spec.AddField(externalorderfulfillment.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(externalorderfulfillment.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(externalorderfulfillment.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(externalorderfulfillment.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(externalorderfulfillment.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(externalorderfulfillment.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(externalorderfulfillment.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ManualURL(); ok {
		_spec.SetField(externalorderfulfillment.FieldManualURL, field.TypeString, value)
	}
	if _u.mutation.ManualURLCleared() {
		_spec.ClearField(externalorderfulfillment.FieldManualURL, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryMessage(); ok {
		_spec.SetField(externalorderfulfillment.FieldDeliveryMessage, field.TypeString, value)
	}
	if _u.mutation.DeliveryMessageCleared() {
		_spec.ClearField(externalorderfulfillment.FieldDeliveryMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(externalorderfulfillment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotifyStatus(); ok {
		_spec.SetField(externalorderfulfillment.FieldNotifyStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailReason(); ok {
		_spec.SetField(externalorderfulfillment.FieldFailReason, field.TypeString, value)
	}
	if _u.mutation.FailReasonCleared() {
		_spec.ClearField(externalorderfulfillment.FieldFailReason, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(externalorderfulfillment.FieldOperator, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		_spec.ClearField(externalorderfulfillment.FieldOperator, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(externalorderfulfillment.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(externalorderfulfillment.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{externalorderfulfillment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExternalOrderFulfillmentUpdateOne is the builder for updating a single ExternalOrderFulfillment entity.
type ExternalOrderFulfillmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExternalOrderFulfillmentMutation
}

// SetPlatform sets the "platform" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetPlatform(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillablePlatform(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformOrderID sets the "platform_order_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetPlatformOrderID(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetPlatformOrderID(v)
	return _u
}

// SetNillablePlatformOrderID sets the "platform_order_id" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillablePlatformOrderID(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetPlatformOrderID(*v)
	}
	return _u
}

// SetBuyerRef sets the "buyer_ref" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetBuyerRef(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetBuyerRef(v)
	return _u
}

// SetNillableBuyerRef sets the "buyer_ref" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableBuyerRef(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetBuyerRef(*v)
	}
	return _u
}

// ClearBuyerRef clears the value of the "buyer_ref" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearBuyerRef() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearBuyerRef()
	return _u
}

// SetSkuCode sets the "sku_code" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetSkuCode(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetSkuCode(v)
	return _u
}

// SetNillableSkuCode sets the "sku_code" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableSkuCode(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetSkuCode(*v)
	}
	return _u
}

// SetSkuName sets the "sku_name" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetSkuName(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetSkuName(v)
	return _u
}

// SetNillableSkuName sets the "sku_name" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableSkuName(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetSkuName(*v)
	}
	return _u
}

// ClearSkuName clears the value of the "sku_name" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearSkuName() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearSkuName()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetAmount(v float64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableAmount(v *float64) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExternalOrderFulfillmentUpdateOne) AddAmount(v float64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetCurrency(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableCurrency(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetRedeemCodeID(v int64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableRedeemCodeID(v *int64) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) AddRedeemCodeID(v int64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearRedeemCodeID() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetRedeemCode sets the "redeem_code" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetRedeemCode(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetRedeemCode(v)
	return _u
}

// SetNillableRedeemCode sets the "redeem_code" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableRedeemCode(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetRedeemCode(*v)
	}
	return _u
}

// ClearRedeemCode clears the value of the "redeem_code" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearRedeemCode() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearRedeemCode()
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetRedeemType(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableRedeemType(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetRedeemValue sets the "redeem_value" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetRedeemValue(v float64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ResetRedeemValue()
	_u.mutation.SetRedeemValue(v)
	return _u
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableRedeemValue(v *float64) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetRedeemValue(*v)
	}
	return _u
}

// AddRedeemValue adds value to the "redeem_value" field.
func (_u *ExternalOrderFulfillmentUpdateOne) AddRedeemValue(v float64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.AddRedeemValue(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetGroupID(v int64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableGroupID(v *int64) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) AddGroupID(v int64) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearGroupID() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetValidityDays(v int) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableValidityDays(v *int) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *ExternalOrderFulfillmentUpdateOne) AddValidityDays(v int) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetExpiresAt(v time.Time) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableExpiresAt(v *time.Time) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearExpiresAt() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetManualURL sets the "manual_url" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetManualURL(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetManualURL(v)
	return _u
}

// SetNillableManualURL sets the "manual_url" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableManualURL(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetManualURL(*v)
	}
	return _u
}

// ClearManualURL clears the value of the "manual_url" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearManualURL() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearManualURL()
	return _u
}

// SetDeliveryMessage sets the "delivery_message" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetDeliveryMessage(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetDeliveryMessage(v)
	return _u
}

// SetNillableDeliveryMessage sets the "delivery_message" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableDeliveryMessage(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetDeliveryMessage(*v)
	}
	return _u
}

// ClearDeliveryMessage clears the value of the "delivery_message" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearDeliveryMessage() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearDeliveryMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetStatus(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableStatus(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotifyStatus sets the "notify_status" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNotifyStatus(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetNotifyStatus(v)
	return _u
}

// SetNillableNotifyStatus sets the "notify_status" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableNotifyStatus(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetNotifyStatus(*v)
	}
	return _u
}

// SetFailReason sets the "fail_reason" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetFailReason(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetFailReason(v)
	return _u
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableFailReason(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetFailReason(*v)
	}
	return _u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearFailReason() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearFailReason()
	return _u
}

// SetOperator sets the "operator" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetOperator(v string) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableOperator(v *string) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// ClearOperator clears the value of the "operator" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearOperator() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearOperator()
	return _u
}

// SetDeliveredAt sets the "delivered_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetDeliveredAt(v time.Time) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetDeliveredAt(v)
	return _u
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableDeliveredAt(v *time.Time) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetDeliveredAt(*v)
	}
	return _u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearDeliveredAt() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearDeliveredAt()
	return _u
}

// SetNotifiedAt sets the "notified_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNotifiedAt(v time.Time) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetNotifiedAt(v)
	return _u
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_u *ExternalOrderFulfillmentUpdateOne) SetNillableNotifiedAt(v *time.Time) *ExternalOrderFulfillmentUpdateOne {
	if v != nil {
		_u.SetNotifiedAt(*v)
	}
	return _u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) ClearNotifiedAt() *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.ClearNotifiedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExternalOrderFulfillmentUpdateOne) SetUpdatedAt(v time.Time) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExternalOrderFulfillmentMutation object of the builder.
func (_u *ExternalOrderFulfillmentUpdateOne) Mutation() *ExternalOrderFulfillmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExternalOrderFulfillmentUpdate builder.
func (_u *ExternalOrderFulfillmentUpdateOne) Where(ps ...predicate.ExternalOrderFulfillment) *ExternalOrderFulfillmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExternalOrderFulfillmentUpdateOne) Select(field string, fields ...string) *ExternalOrderFulfillmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExternalOrderFulfillment entity.
func (_u *ExternalOrderFulfillmentUpdateOne) Save(ctx context.Context) (*ExternalOrderFulfillment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExternalOrderFulfillmentUpdateOne) SaveX(ctx context.Context) *ExternalOrderFulfillment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExternalOrderFulfillmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExternalOrderFulfillmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExternalOrderFulfillmentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := externalorderfulfillment.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExternalOrderFulfillmentUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := externalorderfulfillment.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformOrderID(); ok {
		if err := externalorderfulfillment.PlatformOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_order_id", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.platform_order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BuyerRef(); ok {
		if err := externalorderfulfillment.BuyerRefValidator(v); err != nil {
			return &ValidationError{Name: "buyer_ref", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.buyer_ref": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkuCode(); ok {
		if err := externalorderfulfillment.SkuCodeValidator(v); err != nil {
			return &ValidationError{Name: "sku_code", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.sku_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkuName(); ok {
		if err := externalorderfulfillment.SkuNameValidator(v); err != nil {
			return &ValidationError{Name: "sku_name", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.sku_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := externalorderfulfillment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemCode(); ok {
		if err := externalorderfulfillment.RedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_code", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.redeem_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := externalorderfulfillment.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.redeem_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := externalorderfulfillment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NotifyStatus(); ok {
		if err := externalorderfulfillment.NotifyStatusValidator(v); err != nil {
			return &ValidationError{Name: "notify_status", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.notify_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := externalorderfulfillment.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.operator": %w`, err)}
		}
	}
	return nil
}

func (_u *ExternalOrderFulfillmentUpdateOne) sqlSave(ctx context.Context) (_node *ExternalOrderFulfillment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(externalorderfulfillment.Table, externalorderfulfillment.Columns, sqlgraph.NewFieldSpec(externalorderfulfillment.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExternalOrderFulfillment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, externalorderfulfillment.FieldID)
		for _, f := range fields {
			if !externalorderfulfillment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != externalorderfulfillment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(externalorderfulfillment.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformOrderID(); ok {
		_spec.SetField(externalorderfulfillment.FieldPlatformOrderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BuyerRef(); ok {
		_spec.SetField(externalorderfulfillment.FieldBuyerRef, field.TypeString, value)
	}
	if _u.mutation.BuyerRefCleared() {
		_spec.ClearField(externalorderfulfillment.FieldBuyerRef, field.TypeString)
	}
	if value, ok := _u.mutation.SkuCode(); ok {
		_spec.SetField(externalorderfulfillment.FieldSkuCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkuName(); ok {
		_spec.SetField(externalorderfulfillment.FieldSkuName, field.TypeString, value)
	}
	if _u.mutation.SkuNameCleared() {
		_spec.ClearField(externalorderfulfillment.FieldSkuName, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(externalorderfulfillment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(externalorderfulfillment.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(externalorderfulfillment.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodeIDCleared() {
		_spec.ClearField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RedeemCode(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemCode, field.TypeString, value)
	}
	if _u.mutation.RedeemCodeCleared() {
		_spec.ClearField(externalorderfulfillment.FieldRedeemCode, field.TypeString)
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemValue(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRedeemValue(); ok {
		_spec.AddField(externalorderfulfillment.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(externalorderfulfillment.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(externalorderfulfillment.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(externalorderfulfillment.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(externalorderfulfillment.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(externalorderfulfillment.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(externalorderfulfillment.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ManualURL(); ok {
		_spec.SetField(externalorderfulfillment.FieldManualURL, field.TypeString, value)
	}
	if _u.mutation.ManualURLCleared() {
		_spec.ClearField(externalorderfulfillment.FieldManualURL, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryMessage(); ok {
		_spec.SetField(externalorderfulfillment.FieldDeliveryMessage, field.TypeString, value)
	}
	if _u.mutation.DeliveryMessageCleared() {
		_spec.ClearField(externalorderfulfillment.FieldDeliveryMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(externalorderfulfillment.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NotifyStatus(); ok {
		_spec.SetField(externalorderfulfillment.FieldNotifyStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailReason(); ok {
		_spec.SetField(externalorderfulfillment.FieldFailReason, field.TypeString, value)
	}
	if _u.mutation.FailReasonCleared() {
		_spec.ClearField(externalorderfulfillment.FieldFailReason, field.TypeString)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(externalorderfulfillment.FieldOperator, field.TypeString, value)
	}
	if _u.mutation.OperatorCleared() {
		_spec.ClearField(externalorderfulfillment.FieldOperator, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveredAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldDeliveredAt, field.TypeTime, value)
	}
	if _u.mutation.DeliveredAtCleared() {
		_spec.ClearField(externalorderfulfillment.FieldDeliveredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotifiedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.NotifiedAtCleared() {
		_spec.ClearField(externalorderfulfillment.FieldNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ExternalOrderFulfillment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{externalorderfulfillment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
