// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/externalorderfulfillment"
)

// ExternalOrderFulfillment is the model entity for the ExternalOrderFulfillment schema.
type ExternalOrderFulfillment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// PlatformOrderID holds the value of the "platform_order_id" field.
	PlatformOrderID string `json:"platform_order_id,omitempty"`
	// BuyerRef holds the value of the "buyer_ref" field.
	BuyerRef *string `json:"buyer_ref,omitempty"`
	// SkuCode holds the value of the "sku_code" field.
	SkuCode string `json:"sku_code,omitempty"`
	// SkuName holds the value of the "sku_name" field.
	SkuName *string `json:"sku_name,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID *int64 `json:"redeem_code_id,omitempty"`
	// RedeemCode holds the value of the "redeem_code" field.
	RedeemCode *string `json:"redeem_code,omitempty"`
	// RedeemType holds the value of the "redeem_type" field.
	RedeemType string `json:"redeem_type,omitempty"`
	// RedeemValue holds the value of the "redeem_value" field.
	RedeemValue float64 `json:"redeem_value,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// ManualURL holds the value of the "manual_url" field.
	ManualURL *string `json:"manual_url,omitempty"`
	// DeliveryMessage holds the value of the "delivery_message" field.
	DeliveryMessage *string `json:"delivery_message,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// NotifyStatus holds the value of the "notify_status" field.
	NotifyStatus string `json:"notify_status,omitempty"`
	// FailReason holds the value of the "fail_reason" field.
	FailReason *string `json:"fail_reason,omitempty"`
	// Operator holds the value of the "operator" field.
	Operator *string `json:"operator,omitempty"`
	// DeliveredAt holds the value of the "delivered_at" field.
	DeliveredAt *time.Time `json:"delivered_at,omitempty"`
	// NotifiedAt holds the value of the "notified_at" field.
	NotifiedAt *time.Time `json:"notified_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExternalOrderFulfillment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case externalorderfulfillment.FieldAmount, externalorderfulfillment.FieldRedeemValue:
			values[i] = new(sql.NullFloat64)
		case externalorderfulfillment.FieldID, externalorderfulfillment.FieldRedeemCodeID, externalorderfulfillment.FieldGroupID, externalorderfulfillment.FieldValidityDays:
			values[i] = new(sql.NullInt64)
		case externalorderfulfillment.FieldPlatform, externalorderfulfillment.FieldPlatformOrderID, externalorderfulfillment.FieldBuyerRef, externalorderfulfillment.FieldSkuCode, externalorderfulfillment.FieldSkuName, externalorderfulfillment.FieldCurrency, externalorderfulfillment.FieldRedeemCode, externalorderfulfillment.FieldRedeemType, externalorderfulfillment.FieldManualURL, externalorderfulfillment.FieldDeliveryMessage, externalorderfulfillment.FieldStatus, externalorderfulfillment.FieldNotifyStatus, externalorderfulfillment.FieldFailReason, externalorderfulfillment.FieldOperator:
			values[i] = new(sql.NullString)
		case externalorderfulfillment.FieldExpiresAt, externalorderfulfillment.FieldDeliveredAt, externalorderfulfillment.FieldNotifiedAt, externalorderfulfillment.FieldCreatedAt, externalorderfulfillment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExternalOrderFulfillment fields.
func (_m *ExternalOrderFulfillment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case externalorderfulfillment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case externalorderfulfillment.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case externalorderfulfillment.FieldPlatformOrderID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_order_id", values[i])
			} else if value.Valid {
				_m.PlatformOrderID = value.String
			}
		case externalorderfulfillment.FieldBuyerRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field buyer_ref", values[i])
			} else if value.Valid {
				_m.BuyerRef = new(string)
				*_m.BuyerRef = value.String
			}
		case externalorderfulfillment.FieldSkuCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku_code", values[i])
			} else if value.Valid {
				_m.SkuCode = value.String
			}
		case externalorderfulfillment.FieldSkuName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku_name", values[i])
			} else if value.Valid {
				_m.SkuName = new(string)
				*_m.SkuName = value.String
			}
		case externalorderfulfillment.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case externalorderfulfillment.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case externalorderfulfillment.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = new(int64)
				*_m.RedeemCodeID = value.Int64
			}
		case externalorderfulfillment.FieldRedeemCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code", values[i])
			} else if value.Valid {
				_m.RedeemCode = new(string)
				*_m.RedeemCode = value.String
			}
		case externalorderfulfillment.FieldRedeemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_type", values[i])
			} else if value.Valid {
				_m.RedeemType = value.String
			}
		case externalorderfulfillment.FieldRedeemValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_value", values[i])
			} else if value.Valid {
				_m.RedeemValue = value.Float64
			}
		case externalorderfulfillment.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case externalorderfulfillment.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		case externalorderfulfillment.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case externalorderfulfillment.FieldManualURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_url", values[i])
			} else if value.Valid {
				_m.ManualURL = new(string)
				*_m.ManualURL = value.String
			}
		case externalorderfulfillment.FieldDeliveryMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_message", values[i])
			} else if value.Valid {
				_m.DeliveryMessage = new(string)
				*_m.DeliveryMessage = value.String
			}
		case externalorderfulfillment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case externalorderfulfillment.FieldNotifyStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_status", values[i])
			} else if value.Valid {
				_m.NotifyStatus = value.String
			}
		case externalorderfulfillment.FieldFailReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fail_reason", values[i])
			} else if value.Valid {
				_m.FailReason = new(string)
				*_m.FailReason = value.String
			}
		case externalorderfulfillment.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				_m.Operator = new(string)
				*_m.Operator = value.String
			}
		case externalorderfulfillment.FieldDeliveredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delivered_at", values[i])
			} else if value.Valid {
				_m.DeliveredAt = new(time.Time)
				*_m.DeliveredAt = value.Time
			}
		case externalorderfulfillment.FieldNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field notified_at", values[i])
			} else if value.Valid {
				_m.NotifiedAt = new(time.Time)
				*_m.NotifiedAt = value.Time
			}
		case externalorderfulfillment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case externalorderfulfillment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExternalOrderFulfillment.
// This includes values selected through modifiers, order, etc.
func (_m *ExternalOrderFulfillment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExternalOrderFulfillment.
// Note that you need to call ExternalOrderFulfillment.Unwrap() before calling this method if this ExternalOrderFulfillment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExternalOrderFulfillment) Update() *ExternalOrderFulfillmentUpdateOne {
	return NewExternalOrderFulfillmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExternalOrderFulfillment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExternalOrderFulfillment) Unwrap() *ExternalOrderFulfillment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExternalOrderFulfillment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExternalOrderFulfillment) String() string {
	var builder strings.Builder
	builder.WriteString("ExternalOrderFulfillment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("platform_order_id=")
	builder.WriteString(_m.PlatformOrderID)
	builder.WriteString(", ")
	if v := _m.BuyerRef; v != nil {
		builder.WriteString("buyer_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sku_code=")
	builder.WriteString(_m.SkuCode)
	builder.WriteString(", ")
	if v := _m.SkuName; v != nil {
		builder.WriteString("sku_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	if v := _m.RedeemCodeID; v != nil {
		builder.WriteString("redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RedeemCode; v != nil {
		builder.WriteString("redeem_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("redeem_type=")
	builder.WriteString(_m.RedeemType)
	builder.WriteString(", ")
	builder.WriteString("redeem_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemValue))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ManualURL; v != nil {
		builder.WriteString("manual_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DeliveryMessage; v != nil {
		builder.WriteString("delivery_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("notify_status=")
	builder.WriteString(_m.NotifyStatus)
	builder.WriteString(", ")
	if v := _m.FailReason; v != nil {
		builder.WriteString("fail_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Operator; v != nil {
		builder.WriteString("operator=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DeliveredAt; v != nil {
		builder.WriteString("delivered_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NotifiedAt; v != nil {
		builder.WriteString("notified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExternalOrderFulfillments is a parsable slice of ExternalOrderFulfillment.
type ExternalOrderFulfillments []*ExternalOrderFulfillment
