// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalfulfillmentsku"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ExternalFulfillmentSKUDelete is the builder for deleting a ExternalFulfillmentSKU entity.
type ExternalFulfillmentSKUDelete struct {
	config
	hooks    []Hook
	mutation *ExternalFulfillmentSKUMutation
}

// Where appends a list predicates to the ExternalFulfillmentSKUDelete builder.
func (_d *ExternalFulfillmentSKUDelete) Where(ps ...predicate.ExternalFulfillmentSKU) *ExternalFulfillmentSKUDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExternalFulfillmentSKUDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalFulfillmentSKUDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExternalFulfillmentSKUDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externalfulfillmentsku.Table, sqlgraph.NewFieldSpec(externalfulfillmentsku.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExternalFulfillmentSKUDeleteOne is the builder for deleting a single ExternalFulfillmentSKU entity.
type ExternalFulfillmentSKUDeleteOne struct {
	_d *ExternalFulfillmentSKUDelete
}

// Where appends a list predicates to the ExternalFulfillmentSKUDelete builder.
func (_d *ExternalFulfillmentSKUDeleteOne) Where(ps ...predicate.ExternalFulfillmentSKU) *ExternalFulfillmentSKUDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExternalFulfillmentSKUDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalfulfillmentsku.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalFulfillmentSKUDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
