// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalfulfillmentsku"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ExternalFulfillmentSKUUpdate is the builder for updating ExternalFulfillmentSKU entities.
type ExternalFulfillmentSKUUpdate struct {
	config
	hooks    []Hook
	mutation *ExternalFulfillmentSKUMutation
}

// Where appends a list predicates to the ExternalFulfillmentSKUUpdate builder.
func (_u *ExternalFulfillmentSKUUpdate) Where(ps ...predicate.ExternalFulfillmentSKU) *ExternalFulfillmentSKUUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ExternalFulfillmentSKUUpdate) SetPlatform(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillablePlatform(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetSkuCode sets the "sku_code" field.
func (_u *ExternalFulfillmentSKUUpdate) SetSkuCode(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetSkuCode(v)
	return _u
}

// SetNillableSkuCode sets the "sku_code" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableSkuCode(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetSkuCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ExternalFulfillmentSKUUpdate) SetName(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableName(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExternalFulfillmentSKUUpdate) SetAmount(v float64) *ExternalFulfillmentSKUUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableAmount(v *float64) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExternalFulfillmentSKUUpdate) AddAmount(v float64) *ExternalFulfillmentSKUUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ExternalFulfillmentSKUUpdate) SetCurrency(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableCurrency(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *ExternalFulfillmentSKUUpdate) SetRedeemType(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableRedeemType(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetRedeemValue sets the "redeem_value" field.
func (_u *ExternalFulfillmentSKUUpdate) SetRedeemValue(v float64) *ExternalFulfillmentSKUUpdate {
	_u.mutation.ResetRedeemValue()
	_u.mutation.SetRedeemValue(v)
	return _u
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableRedeemValue(v *float64) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetRedeemValue(*v)
	}
	return _u
}

// AddRedeemValue adds value to the "redeem_value" field.
func (_u *ExternalFulfillmentSKUUpdate) AddRedeemValue(v float64) *ExternalFulfillmentSKUUpdate {
	_u.mutation.AddRedeemValue(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ExternalFulfillmentSKUUpdate) SetGroupID(v int64) *ExternalFulfillmentSKUUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableGroupID(v *int64) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ExternalFulfillmentSKUUpdate) AddGroupID(v int64) *ExternalFulfillmentSKUUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ExternalFulfillmentSKUUpdate) ClearGroupID() *ExternalFulfillmentSKUUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *ExternalFulfillmentSKUUpdate) SetValidityDays(v int) *ExternalFulfillmentSKUUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableValidityDays(v *int) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *ExternalFulfillmentSKUUpdate) AddValidityDays(v int) *ExternalFulfillmentSKUUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetExpiresInDays sets the "expires_in_days" field.
func (_u *ExternalFulfillmentSKUUpdate) SetExpiresInDays(v int) *ExternalFulfillmentSKUUpdate {
	_u.mutation.ResetExpiresInDays()
	_u.mutation.SetExpiresInDays(v)
	return _u
}

// SetNillableExpiresInDays sets the "expires_in_days" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableExpiresInDays(v *int) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetExpiresInDays(*v)
	}
	return _u
}

// AddExpiresInDays adds value to the "expires_in_days" field.
func (_u *ExternalFulfillmentSKUUpdate) AddExpiresInDays(v int) *ExternalFulfillmentSKUUpdate {
	_u.mutation.AddExpiresInDays(v)
	return _u
}

// ClearExpiresInDays clears the value of the "expires_in_days" field.
func (_u *ExternalFulfillmentSKUUpdate) ClearExpiresInDays() *ExternalFulfillmentSKUUpdate {
	_u.mutation.ClearExpiresInDays()
	return _u
}

// SetManualURL sets the "manual_url" field.
func (_u *ExternalFulfillmentSKUUpdate) SetManualURL(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetManualURL(v)
	return _u
}

// SetNillableManualURL sets the "manual_url" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableManualURL(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetManualURL(*v)
	}
	return _u
}

// ClearManualURL clears the value of the "manual_url" field.
func (_u *ExternalFulfillmentSKUUpdate) ClearManualURL() *ExternalFulfillmentSKUUpdate {
	_u.mutation.ClearManualURL()
	return _u
}

// SetDeliveryTemplate sets the "delivery_template" field.
func (_u *ExternalFulfillmentSKUUpdate) SetDeliveryTemplate(v string) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetDeliveryTemplate(v)
	return _u
}

// SetNillableDeliveryTemplate sets the "delivery_template" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableDeliveryTemplate(v *string) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetDeliveryTemplate(*v)
	}
	return _u
}

// ClearDeliveryTemplate clears the value of the "delivery_template" field.
func (_u *ExternalFulfillmentSKUUpdate) ClearDeliveryTemplate() *ExternalFulfillmentSKUUpdate {
	_u.mutation.ClearDeliveryTemplate()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ExternalFulfillmentSKUUpdate) SetEnabled(v bool) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdate) SetNillableEnabled(v *bool) *ExternalFulfillmentSKUUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExternalFulfillmentSKUUpdate) SetUpdatedAt(v time.Time) *ExternalFulfillmentSKUUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExternalFulfillmentSKUMutation object of the builder.
func (_u *ExternalFulfillmentSKUUpdate) Mutation() *ExternalFulfillmentSKUMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExternalFulfillmentSKUUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExternalFulfillmentSKUUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExternalFulfillmentSKUUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExternalFulfillmentSKUUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExternalFulfillmentSKUUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := externalfulfillmentsku.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExternalFulfillmentSKUUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := externalfulfillmentsku.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkuCode(); ok {
		if err := externalfulfillmentsku.SkuCodeValidator(v); err != nil {
			return &ValidationError{Name: "sku_code", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.sku_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := externalfulfillmentsku.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := externalfulfillmentsku.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := externalfulfillmentsku.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.redeem_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ExternalFulfillmentSKUUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(externalfulfillmentsku.Table, externalfulfillmentsku.Columns, sqlgraph.NewFieldSpec(externalfulfillmentsku.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(externalfulfillmentsku.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkuCode(); ok {
		_spec.SetField(externalfulfillmentsku.FieldSkuCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(externalfulfillmentsku.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(externalfulfillmentsku.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(externalfulfillmentsku.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(externalfulfillmentsku.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(externalfulfillmentsku.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemValue(); ok {
		_spec.SetField(externalfulfillmentsku.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRedeemValue(); ok {
		_spec.AddField(externalfulfillmentsku.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(externalfulfillmentsku.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(externalfulfillmentsku.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(externalfulfillmentsku.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(externalfulfillmentsku.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresInDays(); ok {
		_spec.SetField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiresInDays(); ok {
		_spec.AddField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt, value)
	}
	if _u.mutation.ExpiresInDaysCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt)
	}
	if value, ok := _u.mutation.ManualURL(); ok {
		_spec.SetField(externalfulfillmentsku.FieldManualURL, field.TypeString, value)
	}
	if _u.mutation.ManualURLCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldManualURL, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryTemplate(); ok {
		_spec.SetField(externalfulfillmentsku.FieldDeliveryTemplate, field.TypeString, value)
	}
	if _u.mutation.DeliveryTemplateCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldDeliveryTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(externalfulfillmentsku.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(externalfulfillmentsku.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{externalfulfillmentsku.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExternalFulfillmentSKUUpdateOne is the builder for updating a single ExternalFulfillmentSKU entity.
type ExternalFulfillmentSKUUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExternalFulfillmentSKUMutation
}

// SetPlatform sets the "platform" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetPlatform(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillablePlatform(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetSkuCode sets the "sku_code" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetSkuCode(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetSkuCode(v)
	return _u
}

// SetNillableSkuCode sets the "sku_code" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableSkuCode(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetSkuCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetName(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableName(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetAmount(v float64) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableAmount(v *float64) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ExternalFulfillmentSKUUpdateOne) AddAmount(v float64) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetCurrency(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableCurrency(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetRedeemType sets the "redeem_type" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetRedeemType(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetRedeemType(v)
	return _u
}

// SetNillableRedeemType sets the "redeem_type" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableRedeemType(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetRedeemType(*v)
	}
	return _u
}

// SetRedeemValue sets the "redeem_value" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetRedeemValue(v float64) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ResetRedeemValue()
	_u.mutation.SetRedeemValue(v)
	return _u
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableRedeemValue(v *float64) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetRedeemValue(*v)
	}
	return _u
}

// AddRedeemValue adds value to the "redeem_value" field.
func (_u *ExternalFulfillmentSKUUpdateOne) AddRedeemValue(v float64) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.AddRedeemValue(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetGroupID(v int64) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableGroupID(v *int64) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ExternalFulfillmentSKUUpdateOne) AddGroupID(v int64) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ExternalFulfillmentSKUUpdateOne) ClearGroupID() *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetValidityDays(v int) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableValidityDays(v *int) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *ExternalFulfillmentSKUUpdateOne) AddValidityDays(v int) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetExpiresInDays sets the "expires_in_days" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetExpiresInDays(v int) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ResetExpiresInDays()
	_u.mutation.SetExpiresInDays(v)
	return _u
}

// SetNillableExpiresInDays sets the "expires_in_days" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableExpiresInDays(v *int) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetExpiresInDays(*v)
	}
	return _u
}

// AddExpiresInDays adds value to the "expires_in_days" field.
func (_u *ExternalFulfillmentSKUUpdateOne) AddExpiresInDays(v int) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.AddExpiresInDays(v)
	return _u
}

// ClearExpiresInDays clears the value of the "expires_in_days" field.
func (_u *ExternalFulfillmentSKUUpdateOne) ClearExpiresInDays() *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ClearExpiresInDays()
	return _u
}

// SetManualURL sets the "manual_url" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetManualURL(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetManualURL(v)
	return _u
}

// SetNillableManualURL sets the "manual_url" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableManualURL(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetManualURL(*v)
	}
	return _u
}

// ClearManualURL clears the value of the "manual_url" field.
func (_u *ExternalFulfillmentSKUUpdateOne) ClearManualURL() *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ClearManualURL()
	return _u
}

// SetDeliveryTemplate sets the "delivery_template" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetDeliveryTemplate(v string) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetDeliveryTemplate(v)
	return _u
}

// SetNillableDeliveryTemplate sets the "delivery_template" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableDeliveryTemplate(v *string) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetDeliveryTemplate(*v)
	}
	return _u
}

// ClearDeliveryTemplate clears the value of the "delivery_template" field.
func (_u *ExternalFulfillmentSKUUpdateOne) ClearDeliveryTemplate() *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.ClearDeliveryTemplate()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetEnabled(v bool) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ExternalFulfillmentSKUUpdateOne) SetNillableEnabled(v *bool) *ExternalFulfillmentSKUUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExternalFulfillmentSKUUpdateOne) SetUpdatedAt(v time.Time) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExternalFulfillmentSKUMutation object of the builder.
func (_u *ExternalFulfillmentSKUUpdateOne) Mutation() *ExternalFulfillmentSKUMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExternalFulfillmentSKUUpdate builder.
func (_u *ExternalFulfillmentSKUUpdateOne) Where(ps ...predicate.ExternalFulfillmentSKU) *ExternalFulfillmentSKUUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExternalFulfillmentSKUUpdateOne) Select(field string, fields ...string) *ExternalFulfillmentSKUUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExternalFulfillmentSKU entity.
func (_u *ExternalFulfillmentSKUUpdateOne) Save(ctx context.Context) (*ExternalFulfillmentSKU, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExternalFulfillmentSKUUpdateOne) SaveX(ctx context.Context) *ExternalFulfillmentSKU {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExternalFulfillmentSKUUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExternalFulfillmentSKUUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExternalFulfillmentSKUUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := externalfulfillmentsku.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExternalFulfillmentSKUUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := externalfulfillmentsku.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SkuCode(); ok {
		if err := externalfulfillmentsku.SkuCodeValidator(v); err != nil {
			return &ValidationError{Name: "sku_code", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.sku_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := externalfulfillmentsku.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := externalfulfillmentsku.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeemType(); ok {
		if err := externalfulfillmentsku.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.redeem_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ExternalFulfillmentSKUUpdateOne) sqlSave(ctx context.Context) (_node *ExternalFulfillmentSKU, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(externalfulfillmentsku.Table, externalfulfillmentsku.Columns, sqlgraph.NewFieldSpec(externalfulfillmentsku.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExternalFulfillmentSKU.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, externalfulfillmentsku.FieldID)
		for _, f := range fields {
			if !externalfulfillmentsku.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != externalfulfillmentsku.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(externalfulfillmentsku.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.SkuCode(); ok {
		_spec.SetField(externalfulfillmentsku.FieldSkuCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(externalfulfillmentsku.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(externalfulfillmentsku.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(externalfulfillmentsku.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(externalfulfillmentsku.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemType(); ok {
		_spec.SetField(externalfulfillmentsku.FieldRedeemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeemValue(); ok {
		_spec.SetField(externalfulfillmentsku.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRedeemValue(); ok {
		_spec.AddField(externalfulfillmentsku.FieldRedeemValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(externalfulfillmentsku.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(externalfulfillmentsku.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(externalfulfillmentsku.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(externalfulfillmentsku.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresInDays(); ok {
		_spec.SetField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiresInDays(); ok {
		_spec.AddField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt, value)
	}
	if _u.mutation.ExpiresInDaysCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt)
	}
	if value, ok := _u.mutation.ManualURL(); ok {
		_spec.SetField(externalfulfillmentsku.FieldManualURL, field.TypeString, value)
	}
	if _u.mutation.ManualURLCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldManualURL, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryTemplate(); ok {
		_spec.SetField(externalfulfillmentsku.FieldDeliveryTemplate, field.TypeString, value)
	}
	if _u.mutation.DeliveryTemplateCleared() {
		_spec.ClearField(externalfulfillmentsku.FieldDeliveryTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(externalfulfillmentsku.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(externalfulfillmentsku.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ExternalFulfillmentSKU{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{externalfulfillmentsku.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
