// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalfulfillmentsku"
)

// ExternalFulfillmentSKUCreate is the builder for creating a ExternalFulfillmentSKU entity.
type ExternalFulfillmentSKUCreate struct {
	config
	mutation *ExternalFulfillmentSKUMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlatform sets the "platform" field.
func (_c *ExternalFulfillmentSKUCreate) SetPlatform(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillablePlatform(v *string) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetSkuCode sets the "sku_code" field.
func (_c *ExternalFulfillmentSKUCreate) SetSkuCode(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetSkuCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ExternalFulfillmentSKUCreate) SetName(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ExternalFulfillmentSKUCreate) SetAmount(v float64) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableAmount(v *float64) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ExternalFulfillmentSKUCreate) SetCurrency(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableCurrency(v *string) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetRedeemType sets the "redeem_type" field.
func (_c *ExternalFulfillmentSKUCreate) SetRedeemType(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetRedeemType(v)
	return _c
}

// SetRedeemValue sets the "redeem_value" field.
func (_c *ExternalFulfillmentSKUCreate) SetRedeemValue(v float64) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetRedeemValue(v)
	return _c
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableRedeemValue(v *float64) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetRedeemValue(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ExternalFulfillmentSKUCreate) SetGroupID(v int64) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableGroupID(v *int64) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *ExternalFulfillmentSKUCreate) SetValidityDays(v int) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableValidityDays(v *int) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetExpiresInDays sets the "expires_in_days" field.
func (_c *ExternalFulfillmentSKUCreate) SetExpiresInDays(v int) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetExpiresInDays(v)
	return _c
}

// SetNillableExpiresInDays sets the "expires_in_days" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableExpiresInDays(v *int) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetExpiresInDays(*v)
	}
	return _c
}

// SetManualURL sets the "manual_url" field.
func (_c *ExternalFulfillmentSKUCreate) SetManualURL(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetManualURL(v)
	return _c
}

// SetNillableManualURL sets the "manual_url" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableManualURL(v *string) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetManualURL(*v)
	}
	return _c
}

// SetDeliveryTemplate sets the "delivery_template" field.
func (_c *ExternalFulfillmentSKUCreate) SetDeliveryTemplate(v string) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetDeliveryTemplate(v)
	return _c
}

// SetNillableDeliveryTemplate sets the "delivery_template" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableDeliveryTemplate(v *string) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetDeliveryTemplate(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ExternalFulfillmentSKUCreate) SetEnabled(v bool) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableEnabled(v *bool) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExternalFulfillmentSKUCreate) SetCreatedAt(v time.Time) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableCreatedAt(v *time.Time) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExternalFulfillmentSKUCreate) SetUpdatedAt(v time.Time) *ExternalFulfillmentSKUCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExternalFulfillmentSKUCreate) SetNillableUpdatedAt(v *time.Time) *ExternalFulfillmentSKUCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ExternalFulfillmentSKUMutation object of the builder.
func (_c *ExternalFulfillmentSKUCreate) Mutation() *ExternalFulfillmentSKUMutation {
	return _c.mutation
}

// Save creates the ExternalFulfillmentSKU in the database.
func (_c *ExternalFulfillmentSKUCreate) Save(ctx context.Context) (*ExternalFulfillmentSKU, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExternalFulfillmentSKUCreate) SaveX(ctx context.Context) *ExternalFulfillmentSKU {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalFulfillmentSKUCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalFulfillmentSKUCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExternalFulfillmentSKUCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := externalfulfillmentsku.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := externalfulfillmentsku.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := externalfulfillmentsku.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.RedeemValue(); !ok {
		v := externalfulfillmentsku.DefaultRedeemValue
		_c.mutation.SetRedeemValue(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := externalfulfillmentsku.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := externalfulfillmentsku.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := externalfulfillmentsku.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := externalfulfillmentsku.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExternalFulfillmentSKUCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := externalfulfillmentsku.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkuCode(); !ok {
		return &ValidationError{Name: "sku_code", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.sku_code"`)}
	}
	if v, ok := _c.mutation.SkuCode(); ok {
		if err := externalfulfillmentsku.SkuCodeValidator(v); err != nil {
			return &ValidationError{Name: "sku_code", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.sku_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := externalfulfillmentsku.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := externalfulfillmentsku.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedeemType(); !ok {
		return &ValidationError{Name: "redeem_type", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.redeem_type"`)}
	}
	if v, ok := _c.mutation.RedeemType(); ok {
		if err := externalfulfillmentsku.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "ExternalFulfillmentSKU.redeem_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedeemValue(); !ok {
		return &ValidationError{Name: "redeem_value", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.redeem_value"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.validity_days"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExternalFulfillmentSKU.updated_at"`)}
	}
	return nil
}

func (_c *ExternalFulfillmentSKUCreate) sqlSave(ctx context.Context) (*ExternalFulfillmentSKU, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExternalFulfillmentSKUCreate) createSpec() (*ExternalFulfillmentSKU, *sqlgraph.CreateSpec) {
	var (
		_node = &ExternalFulfillmentSKU{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(externalfulfillmentsku.Table, sqlgraph.NewFieldSpec(externalfulfillmentsku.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(externalfulfillmentsku.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.SkuCode(); ok {
		_spec.SetField(externalfulfillmentsku.FieldSkuCode, field.TypeString, value)
		_node.SkuCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(externalfulfillmentsku.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(externalfulfillmentsku.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(externalfulfillmentsku.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RedeemType(); ok {
		_spec.SetField(externalfulfillmentsku.FieldRedeemType, field.TypeString, value)
		_node.RedeemType = value
	}
	if value, ok := _c.mutation.RedeemValue(); ok {
		_spec.SetField(externalfulfillmentsku.FieldRedeemValue, field.TypeFloat64, value)
		_node.RedeemValue = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(externalfulfillmentsku.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(externalfulfillmentsku.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.ExpiresInDays(); ok {
		_spec.SetField(externalfulfillmentsku.FieldExpiresInDays, field.TypeInt, value)
		_node.ExpiresInDays = &value
	}
	if value, ok := _c.mutation.ManualURL(); ok {
		_spec.SetField(externalfulfillmentsku.FieldManualURL, field.TypeString, value)
		_node.ManualURL = &value
	}
	if value, ok := _c.mutation.DeliveryTemplate(); ok {
		_spec.SetField(externalfulfillmentsku.FieldDeliveryTemplate, field.TypeString, value)
		_node.DeliveryTemplate = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(externalfulfillmentsku.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(externalfulfillmentsku.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(externalfulfillmentsku.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalFulfillmentSKU.Create().
//		SetPlatform(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalFulfillmentSKUUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *ExternalFulfillmentSKUCreate) OnConflict(opts ...sql.ConflictOption) *ExternalFulfillmentSKUUpsertOne {
	_c.conflict = opts
	return &ExternalFulfillmentSKUUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalFulfillmentSKU.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExternalFulfillmentSKUCreate) OnConflictColumns(columns ...string) *ExternalFulfillmentSKUUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExternalFulfillmentSKUUpsertOne{
		create: _c,
	}
}

type (
	// ExternalFulfillmentSKUUpsertOne is the builder for "upsert"-ing
	//  one ExternalFulfillmentSKU node.
	ExternalFulfillmentSKUUpsertOne struct {
		create *ExternalFulfillmentSKUCreate
	}

	// ExternalFulfillmentSKUUpsert is the "OnConflict" setter.
	ExternalFulfillmentSKUUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlatform sets the "platform" field.
func (u *ExternalFulfillmentSKUUpsert) SetPlatform(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdatePlatform() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldPlatform)
	return u
}

// SetSkuCode sets the "sku_code" field.
func (u *ExternalFulfillmentSKUUpsert) SetSkuCode(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldSkuCode, v)
	return u
}

// UpdateSkuCode sets the "sku_code" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateSkuCode() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldSkuCode)
	return u
}

// SetName sets the "name" field.
func (u *ExternalFulfillmentSKUUpsert) SetName(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateName() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldName)
	return u
}

// SetAmount sets the "amount" field.
func (u *ExternalFulfillmentSKUUpsert) SetAmount(v float64) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateAmount() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ExternalFulfillmentSKUUpsert) AddAmount(v float64) *ExternalFulfillmentSKUUpsert {
	u.Add(externalfulfillmentsku.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *ExternalFulfillmentSKUUpsert) SetCurrency(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateCurrency() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldCurrency)
	return u
}

// SetRedeemType sets the "redeem_type" field.
func (u *ExternalFulfillmentSKUUpsert) SetRedeemType(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldRedeemType, v)
	return u
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateRedeemType() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldRedeemType)
	return u
}

// SetRedeemValue sets the "redeem_value" field.
func (u *ExternalFulfillmentSKUUpsert) SetRedeemValue(v float64) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldRedeemValue, v)
	return u
}

// UpdateRedeemValue sets the "redeem_value" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateRedeemValue() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldRedeemValue)
	return u
}

// AddRedeemValue adds v to the "redeem_value" field.
func (u *ExternalFulfillmentSKUUpsert) AddRedeemValue(v float64) *ExternalFulfillmentSKUUpsert {
	u.Add(externalfulfillmentsku.FieldRedeemValue, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ExternalFulfillmentSKUUpsert) SetGroupID(v int64) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateGroupID() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ExternalFulfillmentSKUUpsert) AddGroupID(v int64) *ExternalFulfillmentSKUUpsert {
	u.Add(externalfulfillmentsku.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ExternalFulfillmentSKUUpsert) ClearGroupID() *ExternalFulfillmentSKUUpsert {
	u.SetNull(externalfulfillmentsku.FieldGroupID)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *ExternalFulfillmentSKUUpsert) SetValidityDays(v int) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateValidityDays() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ExternalFulfillmentSKUUpsert) AddValidityDays(v int) *ExternalFulfillmentSKUUpsert {
	u.Add(externalfulfillmentsku.FieldValidityDays, v)
	return u
}

// SetExpiresInDays sets the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsert) SetExpiresInDays(v int) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldExpiresInDays, v)
	return u
}

// UpdateExpiresInDays sets the "expires_in_days" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateExpiresInDays() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldExpiresInDays)
	return u
}

// AddExpiresInDays adds v to the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsert) AddExpiresInDays(v int) *ExternalFulfillmentSKUUpsert {
	u.Add(externalfulfillmentsku.FieldExpiresInDays, v)
	return u
}

// ClearExpiresInDays clears the value of the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsert) ClearExpiresInDays() *ExternalFulfillmentSKUUpsert {
	u.SetNull(externalfulfillmentsku.FieldExpiresInDays)
	return u
}

// SetManualURL sets the "manual_url" field.
func (u *ExternalFulfillmentSKUUpsert) SetManualURL(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldManualURL, v)
	return u
}

// UpdateManualURL sets the "manual_url" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateManualURL() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldManualURL)
	return u
}

// ClearManualURL clears the value of the "manual_url" field.
func (u *ExternalFulfillmentSKUUpsert) ClearManualURL() *ExternalFulfillmentSKUUpsert {
	u.SetNull(externalfulfillmentsku.FieldManualURL)
	return u
}

// SetDeliveryTemplate sets the "delivery_template" field.
func (u *ExternalFulfillmentSKUUpsert) SetDeliveryTemplate(v string) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldDeliveryTemplate, v)
	return u
}

// UpdateDeliveryTemplate sets the "delivery_template" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateDeliveryTemplate() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldDeliveryTemplate)
	return u
}

// ClearDeliveryTemplate clears the value of the "delivery_template" field.
func (u *ExternalFulfillmentSKUUpsert) ClearDeliveryTemplate() *ExternalFulfillmentSKUUpsert {
	u.SetNull(externalfulfillmentsku.FieldDeliveryTemplate)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ExternalFulfillmentSKUUpsert) SetEnabled(v bool) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateEnabled() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalFulfillmentSKUUpsert) SetUpdatedAt(v time.Time) *ExternalFulfillmentSKUUpsert {
	u.Set(externalfulfillmentsku.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsert) UpdateUpdatedAt() *ExternalFulfillmentSKUUpsert {
	u.SetExcluded(externalfulfillmentsku.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ExternalFulfillmentSKU.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalFulfillmentSKUUpsertOne) UpdateNewValues() *ExternalFulfillmentSKUUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(externalfulfillmentsku.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalFulfillmentSKU.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExternalFulfillmentSKUUpsertOne) Ignore() *ExternalFulfillmentSKUUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalFulfillmentSKUUpsertOne) DoNothing() *ExternalFulfillmentSKUUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalFulfillmentSKUCreate.OnConflict
// documentation for more info.
func (u *ExternalFulfillmentSKUUpsertOne) Update(set func(*ExternalFulfillmentSKUUpsert)) *ExternalFulfillmentSKUUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalFulfillmentSKUUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetPlatform(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdatePlatform() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdatePlatform()
	})
}

// SetSkuCode sets the "sku_code" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetSkuCode(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetSkuCode(v)
	})
}

// UpdateSkuCode sets the "sku_code" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateSkuCode() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateSkuCode()
	})
}

// SetName sets the "name" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetName(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateName() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateName()
	})
}

// SetAmount sets the "amount" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetAmount(v float64) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ExternalFulfillmentSKUUpsertOne) AddAmount(v float64) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateAmount() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetCurrency(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateCurrency() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateCurrency()
	})
}

// SetRedeemType sets the "redeem_type" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetRedeemType(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetRedeemType(v)
	})
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateRedeemType() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateRedeemType()
	})
}

// SetRedeemValue sets the "redeem_value" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetRedeemValue(v float64) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetRedeemValue(v)
	})
}

// AddRedeemValue adds v to the "redeem_value" field.
func (u *ExternalFulfillmentSKUUpsertOne) AddRedeemValue(v float64) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddRedeemValue(v)
	})
}

// UpdateRedeemValue sets the "redeem_value" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateRedeemValue() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateRedeemValue()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetGroupID(v int64) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ExternalFulfillmentSKUUpsertOne) AddGroupID(v int64) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateGroupID() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ExternalFulfillmentSKUUpsertOne) ClearGroupID() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetValidityDays(v int) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ExternalFulfillmentSKUUpsertOne) AddValidityDays(v int) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateValidityDays() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateValidityDays()
	})
}

// SetExpiresInDays sets the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetExpiresInDays(v int) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetExpiresInDays(v)
	})
}

// AddExpiresInDays adds v to the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsertOne) AddExpiresInDays(v int) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddExpiresInDays(v)
	})
}

// UpdateExpiresInDays sets the "expires_in_days" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateExpiresInDays() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateExpiresInDays()
	})
}

// ClearExpiresInDays clears the value of the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsertOne) ClearExpiresInDays() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearExpiresInDays()
	})
}

// SetManualURL sets the "manual_url" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetManualURL(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetManualURL(v)
	})
}

// UpdateManualURL sets the "manual_url" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateManualURL() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateManualURL()
	})
}

// ClearManualURL clears the value of the "manual_url" field.
func (u *ExternalFulfillmentSKUUpsertOne) ClearManualURL() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearManualURL()
	})
}

// SetDeliveryTemplate sets the "delivery_template" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetDeliveryTemplate(v string) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetDeliveryTemplate(v)
	})
}

// UpdateDeliveryTemplate sets the "delivery_template" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateDeliveryTemplate() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateDeliveryTemplate()
	})
}

// ClearDeliveryTemplate clears the value of the "delivery_template" field.
func (u *ExternalFulfillmentSKUUpsertOne) ClearDeliveryTemplate() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearDeliveryTemplate()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetEnabled(v bool) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateEnabled() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalFulfillmentSKUUpsertOne) SetUpdatedAt(v time.Time) *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertOne) UpdateUpdatedAt() *ExternalFulfillmentSKUUpsertOne {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExternalFulfillmentSKUUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalFulfillmentSKUCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalFulfillmentSKUUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExternalFulfillmentSKUUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExternalFulfillmentSKUUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExternalFulfillmentSKUCreateBulk is the builder for creating many ExternalFulfillmentSKU entities in bulk.
type ExternalFulfillmentSKUCreateBulk struct {
	config
	err      error
	builders []*ExternalFulfillmentSKUCreate
	conflict []sql.ConflictOption
}

// Save creates the ExternalFulfillmentSKU entities in the database.
func (_c *ExternalFulfillmentSKUCreateBulk) Save(ctx context.Context) ([]*ExternalFulfillmentSKU, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExternalFulfillmentSKU, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExternalFulfillmentSKUMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExternalFulfillmentSKUCreateBulk) SaveX(ctx context.Context) []*ExternalFulfillmentSKU {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalFulfillmentSKUCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalFulfillmentSKUCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalFulfillmentSKU.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalFulfillmentSKUUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *ExternalFulfillmentSKUCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExternalFulfillmentSKUUpsertBulk {
	_c.conflict = opts
	return &ExternalFulfillmentSKUUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalFulfillmentSKU.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExternalFulfillmentSKUCreateBulk) OnConflictColumns(columns ...string) *ExternalFulfillmentSKUUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExternalFulfillmentSKUUpsertBulk{
		create: _c,
	}
}

// ExternalFulfillmentSKUUpsertBulk is the builder for "upsert"-ing
// a bulk of ExternalFulfillmentSKU nodes.
type ExternalFulfillmentSKUUpsertBulk struct {
	create *ExternalFulfillmentSKUCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExternalFulfillmentSKU.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateNewValues() *ExternalFulfillmentSKUUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(externalfulfillmentsku.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalFulfillmentSKU.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExternalFulfillmentSKUUpsertBulk) Ignore() *ExternalFulfillmentSKUUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalFulfillmentSKUUpsertBulk) DoNothing() *ExternalFulfillmentSKUUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalFulfillmentSKUCreateBulk.OnConflict
// documentation for more info.
func (u *ExternalFulfillmentSKUUpsertBulk) Update(set func(*ExternalFulfillmentSKUUpsert)) *ExternalFulfillmentSKUUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalFulfillmentSKUUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetPlatform(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdatePlatform() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdatePlatform()
	})
}

// SetSkuCode sets the "sku_code" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetSkuCode(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetSkuCode(v)
	})
}

// UpdateSkuCode sets the "sku_code" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateSkuCode() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateSkuCode()
	})
}

// SetName sets the "name" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetName(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateName() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateName()
	})
}

// SetAmount sets the "amount" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetAmount(v float64) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ExternalFulfillmentSKUUpsertBulk) AddAmount(v float64) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateAmount() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetCurrency(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateCurrency() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateCurrency()
	})
}

// SetRedeemType sets the "redeem_type" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetRedeemType(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetRedeemType(v)
	})
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateRedeemType() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateRedeemType()
	})
}

// SetRedeemValue sets the "redeem_value" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetRedeemValue(v float64) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetRedeemValue(v)
	})
}

// AddRedeemValue adds v to the "redeem_value" field.
func (u *ExternalFulfillmentSKUUpsertBulk) AddRedeemValue(v float64) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddRedeemValue(v)
	})
}

// UpdateRedeemValue sets the "redeem_value" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateRedeemValue() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateRedeemValue()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetGroupID(v int64) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ExternalFulfillmentSKUUpsertBulk) AddGroupID(v int64) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateGroupID() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ExternalFulfillmentSKUUpsertBulk) ClearGroupID() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetValidityDays(v int) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ExternalFulfillmentSKUUpsertBulk) AddValidityDays(v int) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateValidityDays() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateValidityDays()
	})
}

// SetExpiresInDays sets the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetExpiresInDays(v int) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetExpiresInDays(v)
	})
}

// AddExpiresInDays adds v to the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsertBulk) AddExpiresInDays(v int) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.AddExpiresInDays(v)
	})
}

// UpdateExpiresInDays sets the "expires_in_days" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateExpiresInDays() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateExpiresInDays()
	})
}

// ClearExpiresInDays clears the value of the "expires_in_days" field.
func (u *ExternalFulfillmentSKUUpsertBulk) ClearExpiresInDays() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearExpiresInDays()
	})
}

// SetManualURL sets the "manual_url" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetManualURL(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetManualURL(v)
	})
}

// UpdateManualURL sets the "manual_url" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateManualURL() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateManualURL()
	})
}

// ClearManualURL clears the value of the "manual_url" field.
func (u *ExternalFulfillmentSKUUpsertBulk) ClearManualURL() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearManualURL()
	})
}

// SetDeliveryTemplate sets the "delivery_template" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetDeliveryTemplate(v string) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetDeliveryTemplate(v)
	})
}

// UpdateDeliveryTemplate sets the "delivery_template" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateDeliveryTemplate() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateDeliveryTemplate()
	})
}

// ClearDeliveryTemplate clears the value of the "delivery_template" field.
func (u *ExternalFulfillmentSKUUpsertBulk) ClearDeliveryTemplate() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.ClearDeliveryTemplate()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetEnabled(v bool) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateEnabled() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalFulfillmentSKUUpsertBulk) SetUpdatedAt(v time.Time) *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalFulfillmentSKUUpsertBulk) UpdateUpdatedAt() *ExternalFulfillmentSKUUpsertBulk {
	return u.Update(func(s *ExternalFulfillmentSKUUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExternalFulfillmentSKUUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExternalFulfillmentSKUCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalFulfillmentSKUCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalFulfillmentSKUUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
