// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/externalfulfillmentsku"
)

// ExternalFulfillmentSKU is the model entity for the ExternalFulfillmentSKU schema.
type ExternalFulfillmentSKU struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// SkuCode holds the value of the "sku_code" field.
	SkuCode string `json:"sku_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// RedeemType holds the value of the "redeem_type" field.
	RedeemType string `json:"redeem_type,omitempty"`
	// RedeemValue holds the value of the "redeem_value" field.
	RedeemValue float64 `json:"redeem_value,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// ValidityDays holds the value of the "validity_days" field.
	ValidityDays int `json:"validity_days,omitempty"`
	// ExpiresInDays holds the value of the "expires_in_days" field.
	ExpiresInDays *int `json:"expires_in_days,omitempty"`
	// ManualURL holds the value of the "manual_url" field.
	ManualURL *string `json:"manual_url,omitempty"`
	// DeliveryTemplate holds the value of the "delivery_template" field.
	DeliveryTemplate *string `json:"delivery_template,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExternalFulfillmentSKU) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case externalfulfillmentsku.FieldEnabled:
			values[i] = new(sql.NullBool)
		case externalfulfillmentsku.FieldAmount, externalfulfillmentsku.FieldRedeemValue:
			values[i] = new(sql.NullFloat64)
		case externalfulfillmentsku.FieldID, externalfulfillmentsku.FieldGroupID, externalfulfillmentsku.FieldValidityDays, externalfulfillmentsku.FieldExpiresInDays:
			values[i] = new(sql.NullInt64)
		case externalfulfillmentsku.FieldPlatform, externalfulfillmentsku.FieldSkuCode, externalfulfillmentsku.FieldName, externalfulfillmentsku.FieldCurrency, externalfulfillmentsku.FieldRedeemType, externalfulfillmentsku.FieldManualURL, externalfulfillmentsku.FieldDeliveryTemplate:
			values[i] = new(sql.NullString)
		case externalfulfillmentsku.FieldCreatedAt, externalfulfillmentsku.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExternalFulfillmentSKU fields.
func (_m *ExternalFulfillmentSKU) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case externalfulfillmentsku.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case externalfulfillmentsku.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case externalfulfillmentsku.FieldSkuCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku_code", values[i])
			} else if value.Valid {
				_m.SkuCode = value.String
			}
		case externalfulfillmentsku.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case externalfulfillmentsku.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case externalfulfillmentsku.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case externalfulfillmentsku.FieldRedeemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_type", values[i])
			} else if value.Valid {
				_m.RedeemType = value.String
			}
		case externalfulfillmentsku.FieldRedeemValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_value", values[i])
			} else if value.Valid {
				_m.RedeemValue = value.Float64
			}
		case externalfulfillmentsku.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case externalfulfillmentsku.FieldValidityDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days", values[i])
			} else if value.Valid {
				_m.ValidityDays = int(value.Int64)
			}
		case externalfulfillmentsku.FieldExpiresInDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expires_in_days", values[i])
			} else if value.Valid {
				_m.ExpiresInDays = new(int)
				*_m.ExpiresInDays = int(value.Int64)
			}
		case externalfulfillmentsku.FieldManualURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manual_url", values[i])
			} else if value.Valid {
				_m.ManualURL = new(string)
				*_m.ManualURL = value.String
			}
		case externalfulfillmentsku.FieldDeliveryTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_template", values[i])
			} else if value.Valid {
				_m.DeliveryTemplate = new(string)
				*_m.DeliveryTemplate = value.String
			}
		case externalfulfillmentsku.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case externalfulfillmentsku.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case externalfulfillmentsku.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExternalFulfillmentSKU.
// This includes values selected through modifiers, order, etc.
func (_m *ExternalFulfillmentSKU) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExternalFulfillmentSKU.
// Note that you need to call ExternalFulfillmentSKU.Unwrap() before calling this method if this ExternalFulfillmentSKU
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExternalFulfillmentSKU) Update() *ExternalFulfillmentSKUUpdateOne {
	return NewExternalFulfillmentSKUClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExternalFulfillmentSKU entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExternalFulfillmentSKU) Unwrap() *ExternalFulfillmentSKU {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExternalFulfillmentSKU is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExternalFulfillmentSKU) String() string {
	var builder strings.Builder
	builder.WriteString("ExternalFulfillmentSKU(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("sku_code=")
	builder.WriteString(_m.SkuCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("redeem_type=")
	builder.WriteString(_m.RedeemType)
	builder.WriteString(", ")
	builder.WriteString("redeem_value=")
	builder.WriteString(fmt.Sprintf("%v", _m.RedeemValue))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("validity_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDays))
	builder.WriteString(", ")
	if v := _m.ExpiresInDays; v != nil {
		builder.WriteString("expires_in_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ManualURL; v != nil {
		builder.WriteString("manual_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DeliveryTemplate; v != nil {
		builder.WriteString("delivery_template=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExternalFulfillmentSKUs is a parsable slice of ExternalFulfillmentSKU.
type ExternalFulfillmentSKUs []*ExternalFulfillmentSKU
