// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalorderfulfillment"
)

// ExternalOrderFulfillmentCreate is the builder for creating a ExternalOrderFulfillment entity.
type ExternalOrderFulfillmentCreate struct {
	config
	mutation *ExternalOrderFulfillmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlatform sets the "platform" field.
func (_c *ExternalOrderFulfillmentCreate) SetPlatform(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillablePlatform(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetPlatformOrderID sets the "platform_order_id" field.
func (_c *ExternalOrderFulfillmentCreate) SetPlatformOrderID(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetPlatformOrderID(v)
	return _c
}

// SetBuyerRef sets the "buyer_ref" field.
func (_c *ExternalOrderFulfillmentCreate) SetBuyerRef(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetBuyerRef(v)
	return _c
}

// SetNillableBuyerRef sets the "buyer_ref" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableBuyerRef(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetBuyerRef(*v)
	}
	return _c
}

// SetSkuCode sets the "sku_code" field.
func (_c *ExternalOrderFulfillmentCreate) SetSkuCode(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetSkuCode(v)
	return _c
}

// SetSkuName sets the "sku_name" field.
func (_c *ExternalOrderFulfillmentCreate) SetSkuName(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetSkuName(v)
	return _c
}

// SetNillableSkuName sets the "sku_name" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableSkuName(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetSkuName(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *ExternalOrderFulfillmentCreate) SetAmount(v float64) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableAmount(v *float64) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ExternalOrderFulfillmentCreate) SetCurrency(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableCurrency(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *ExternalOrderFulfillmentCreate) SetRedeemCodeID(v int64) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableRedeemCodeID(v *int64) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetRedeemCodeID(*v)
	}
	return _c
}

// SetRedeemCode sets the "redeem_code" field.
func (_c *ExternalOrderFulfillmentCreate) SetRedeemCode(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetRedeemCode(v)
	return _c
}

// SetNillableRedeemCode sets the "redeem_code" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableRedeemCode(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetRedeemCode(*v)
	}
	return _c
}

// SetRedeemType sets the "redeem_type" field.
func (_c *ExternalOrderFulfillmentCreate) SetRedeemType(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetRedeemType(v)
	return _c
}

// SetRedeemValue sets the "redeem_value" field.
func (_c *ExternalOrderFulfillmentCreate) SetRedeemValue(v float64) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetRedeemValue(v)
	return _c
}

// SetNillableRedeemValue sets the "redeem_value" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableRedeemValue(v *float64) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetRedeemValue(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ExternalOrderFulfillmentCreate) SetGroupID(v int64) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableGroupID(v *int64) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetValidityDays sets the "validity_days" field.
func (_c *ExternalOrderFulfillmentCreate) SetValidityDays(v int) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetValidityDays(v)
	return _c
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableValidityDays(v *int) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetValidityDays(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ExternalOrderFulfillmentCreate) SetExpiresAt(v time.Time) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableExpiresAt(v *time.Time) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetManualURL sets the "manual_url" field.
func (_c *ExternalOrderFulfillmentCreate) SetManualURL(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetManualURL(v)
	return _c
}

// SetNillableManualURL sets the "manual_url" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableManualURL(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetManualURL(*v)
	}
	return _c
}

// SetDeliveryMessage sets the "delivery_message" field.
func (_c *ExternalOrderFulfillmentCreate) SetDeliveryMessage(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetDeliveryMessage(v)
	return _c
}

// SetNillableDeliveryMessage sets the "delivery_message" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableDeliveryMessage(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetDeliveryMessage(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExternalOrderFulfillmentCreate) SetStatus(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableStatus(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotifyStatus sets the "notify_status" field.
func (_c *ExternalOrderFulfillmentCreate) SetNotifyStatus(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetNotifyStatus(v)
	return _c
}

// SetNillableNotifyStatus sets the "notify_status" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableNotifyStatus(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetNotifyStatus(*v)
	}
	return _c
}

// SetFailReason sets the "fail_reason" field.
func (_c *ExternalOrderFulfillmentCreate) SetFailReason(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetFailReason(v)
	return _c
}

// SetNillableFailReason sets the "fail_reason" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableFailReason(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetFailReason(*v)
	}
	return _c
}

// SetOperator sets the "operator" field.
func (_c *ExternalOrderFulfillmentCreate) SetOperator(v string) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableOperator(v *string) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetOperator(*v)
	}
	return _c
}

// SetDeliveredAt sets the "delivered_at" field.
func (_c *ExternalOrderFulfillmentCreate) SetDeliveredAt(v time.Time) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetDeliveredAt(v)
	return _c
}

// SetNillableDeliveredAt sets the "delivered_at" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableDeliveredAt(v *time.Time) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetDeliveredAt(*v)
	}
	return _c
}

// SetNotifiedAt sets the "notified_at" field.
func (_c *ExternalOrderFulfillmentCreate) SetNotifiedAt(v time.Time) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetNotifiedAt(v)
	return _c
}

// SetNillableNotifiedAt sets the "notified_at" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableNotifiedAt(v *time.Time) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetNotifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExternalOrderFulfillmentCreate) SetCreatedAt(v time.Time) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableCreatedAt(v *time.Time) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExternalOrderFulfillmentCreate) SetUpdatedAt(v time.Time) *ExternalOrderFulfillmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExternalOrderFulfillmentCreate) SetNillableUpdatedAt(v *time.Time) *ExternalOrderFulfillmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ExternalOrderFulfillmentMutation object of the builder.
func (_c *ExternalOrderFulfillmentCreate) Mutation() *ExternalOrderFulfillmentMutation {
	return _c.mutation
}

// Save creates the ExternalOrderFulfillment in the database.
func (_c *ExternalOrderFulfillmentCreate) Save(ctx context.Context) (*ExternalOrderFulfillment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExternalOrderFulfillmentCreate) SaveX(ctx context.Context) *ExternalOrderFulfillment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalOrderFulfillmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalOrderFulfillmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExternalOrderFulfillmentCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := externalorderfulfillment.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := externalorderfulfillment.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := externalorderfulfillment.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.RedeemValue(); !ok {
		v := externalorderfulfillment.DefaultRedeemValue
		_c.mutation.SetRedeemValue(v)
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		v := externalorderfulfillment.DefaultValidityDays
		_c.mutation.SetValidityDays(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := externalorderfulfillment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.NotifyStatus(); !ok {
		v := externalorderfulfillment.DefaultNotifyStatus
		_c.mutation.SetNotifyStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := externalorderfulfillment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := externalorderfulfillment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExternalOrderFulfillmentCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := externalorderfulfillment.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformOrderID(); !ok {
		return &ValidationError{Name: "platform_order_id", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.platform_order_id"`)}
	}
	if v, ok := _c.mutation.PlatformOrderID(); ok {
		if err := externalorderfulfillment.PlatformOrderIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_order_id", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.platform_order_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BuyerRef(); ok {
		if err := externalorderfulfillment.BuyerRefValidator(v); err != nil {
			return &ValidationError{Name: "buyer_ref", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.buyer_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SkuCode(); !ok {
		return &ValidationError{Name: "sku_code", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.sku_code"`)}
	}
	if v, ok := _c.mutation.SkuCode(); ok {
		if err := externalorderfulfillment.SkuCodeValidator(v); err != nil {
			return &ValidationError{Name: "sku_code", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.sku_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SkuName(); ok {
		if err := externalorderfulfillment.SkuNameValidator(v); err != nil {
			return &ValidationError{Name: "sku_name", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.sku_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := externalorderfulfillment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.currency": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RedeemCode(); ok {
		if err := externalorderfulfillment.RedeemCodeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_code", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.redeem_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedeemType(); !ok {
		return &ValidationError{Name: "redeem_type", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.redeem_type"`)}
	}
	if v, ok := _c.mutation.RedeemType(); ok {
		if err := externalorderfulfillment.RedeemTypeValidator(v); err != nil {
			return &ValidationError{Name: "redeem_type", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.redeem_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedeemValue(); !ok {
		return &ValidationError{Name: "redeem_value", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.redeem_value"`)}
	}
	if _, ok := _c.mutation.ValidityDays(); !ok {
		return &ValidationError{Name: "validity_days", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.validity_days"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := externalorderfulfillment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotifyStatus(); !ok {
		return &ValidationError{Name: "notify_status", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.notify_status"`)}
	}
	if v, ok := _c.mutation.NotifyStatus(); ok {
		if err := externalorderfulfillment.NotifyStatusValidator(v); err != nil {
			return &ValidationError{Name: "notify_status", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.notify_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Operator(); ok {
		if err := externalorderfulfillment.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "ExternalOrderFulfillment.operator": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExternalOrderFulfillment.updated_at"`)}
	}
	return nil
}

func (_c *ExternalOrderFulfillmentCreate) sqlSave(ctx context.Context) (*ExternalOrderFulfillment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExternalOrderFulfillmentCreate) createSpec() (*ExternalOrderFulfillment, *sqlgraph.CreateSpec) {
	var (
		_node = &ExternalOrderFulfillment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(externalorderfulfillment.Table, sqlgraph.NewFieldSpec(externalorderfulfillment.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(externalorderfulfillment.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.PlatformOrderID(); ok {
		_spec.SetField(externalorderfulfillment.FieldPlatformOrderID, field.TypeString, value)
		_node.PlatformOrderID = value
	}
	if value, ok := _c.mutation.BuyerRef(); ok {
		_spec.SetField(externalorderfulfillment.FieldBuyerRef, field.TypeString, value)
		_node.BuyerRef = &value
	}
	if value, ok := _c.mutation.SkuCode(); ok {
		_spec.SetField(externalorderfulfillment.FieldSkuCode, field.TypeString, value)
		_node.SkuCode = value
	}
	if value, ok := _c.mutation.SkuName(); ok {
		_spec.SetField(externalorderfulfillment.FieldSkuName, field.TypeString, value)
		_node.SkuName = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(externalorderfulfillment.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(externalorderfulfillment.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = &value
	}
	if value, ok := _c.mutation.RedeemCode(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemCode, field.TypeString, value)
		_node.RedeemCode = &value
	}
	if value, ok := _c.mutation.RedeemType(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemType, field.TypeString, value)
		_node.RedeemType = value
	}
	if value, ok := _c.mutation.RedeemValue(); ok {
		_spec.SetField(externalorderfulfillment.FieldRedeemValue, field.TypeFloat64, value)
		_node.RedeemValue = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(externalorderfulfillment.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.ValidityDays(); ok {
		_spec.SetField(externalorderfulfillment.FieldValidityDays, field.TypeInt, value)
		_node.ValidityDays = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.ManualURL(); ok {
		_spec.SetField(externalorderfulfillment.FieldManualURL, field.TypeString, value)
		_node.ManualURL = &value
	}
	if value, ok := _c.mutation.DeliveryMessage(); ok {
		_spec.SetField(externalorderfulfillment.FieldDeliveryMessage, field.TypeString, value)
		_node.DeliveryMessage = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(externalorderfulfillment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.NotifyStatus(); ok {
		_spec.SetField(externalorderfulfillment.FieldNotifyStatus, field.TypeString, value)
		_node.NotifyStatus = value
	}
	if value, ok := _c.mutation.FailReason(); ok {
		_spec.SetField(externalorderfulfillment.FieldFailReason, field.TypeString, value)
		_node.FailReason = &value
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(externalorderfulfillment.FieldOperator, field.TypeString, value)
		_node.Operator = &value
	}
	if value, ok := _c.mutation.DeliveredAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldDeliveredAt, field.TypeTime, value)
		_node.DeliveredAt = &value
	}
	if value, ok := _c.mutation.NotifiedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldNotifiedAt, field.TypeTime, value)
		_node.NotifiedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(externalorderfulfillment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalOrderFulfillment.Create().
//		SetPlatform(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalOrderFulfillmentUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *ExternalOrderFulfillmentCreate) OnConflict(opts ...sql.ConflictOption) *ExternalOrderFulfillmentUpsertOne {
	_c.conflict = opts
	return &ExternalOrderFulfillmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalOrderFulfillment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExternalOrderFulfillmentCreate) OnConflictColumns(columns ...string) *ExternalOrderFulfillmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExternalOrderFulfillmentUpsertOne{
		create: _c,
	}
}

type (
	// ExternalOrderFulfillmentUpsertOne is the builder for "upsert"-ing
	//  one ExternalOrderFulfillment node.
	ExternalOrderFulfillmentUpsertOne struct {
		create *ExternalOrderFulfillmentCreate
	}

	// ExternalOrderFulfillmentUpsert is the "OnConflict" setter.
	ExternalOrderFulfillmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlatform sets the "platform" field.
func (u *ExternalOrderFulfillmentUpsert) SetPlatform(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdatePlatform() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldPlatform)
	return u
}

// SetPlatformOrderID sets the "platform_order_id" field.
func (u *ExternalOrderFulfillmentUpsert) SetPlatformOrderID(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldPlatformOrderID, v)
	return u
}

// UpdatePlatformOrderID sets the "platform_order_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdatePlatformOrderID() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldPlatformOrderID)
	return u
}

// SetBuyerRef sets the "buyer_ref" field.
func (u *ExternalOrderFulfillmentUpsert) SetBuyerRef(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldBuyerRef, v)
	return u
}

// UpdateBuyerRef sets the "buyer_ref" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateBuyerRef() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldBuyerRef)
	return u
}

// ClearBuyerRef clears the value of the "buyer_ref" field.
func (u *ExternalOrderFulfillmentUpsert) ClearBuyerRef() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldBuyerRef)
	return u
}

// SetSkuCode sets the "sku_code" field.
func (u *ExternalOrderFulfillmentUpsert) SetSkuCode(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldSkuCode, v)
	return u
}

// UpdateSkuCode sets the "sku_code" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateSkuCode() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldSkuCode)
	return u
}

// SetSkuName sets the "sku_name" field.
func (u *ExternalOrderFulfillmentUpsert) SetSkuName(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldSkuName, v)
	return u
}

// UpdateSkuName sets the "sku_name" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateSkuName() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldSkuName)
	return u
}

// ClearSkuName clears the value of the "sku_name" field.
func (u *ExternalOrderFulfillmentUpsert) ClearSkuName() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldSkuName)
	return u
}

// SetAmount sets the "amount" field.
func (u *ExternalOrderFulfillmentUpsert) SetAmount(v float64) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateAmount() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *ExternalOrderFulfillmentUpsert) AddAmount(v float64) *ExternalOrderFulfillmentUpsert {
	u.Add(externalorderfulfillment.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *ExternalOrderFulfillmentUpsert) SetCurrency(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateCurrency() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldCurrency)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsert) SetRedeemCodeID(v int64) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateRedeemCodeID() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsert) AddRedeemCodeID(v int64) *ExternalOrderFulfillmentUpsert {
	u.Add(externalorderfulfillment.FieldRedeemCodeID, v)
	return u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsert) ClearRedeemCodeID() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldRedeemCodeID)
	return u
}

// SetRedeemCode sets the "redeem_code" field.
func (u *ExternalOrderFulfillmentUpsert) SetRedeemCode(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldRedeemCode, v)
	return u
}

// UpdateRedeemCode sets the "redeem_code" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateRedeemCode() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldRedeemCode)
	return u
}

// ClearRedeemCode clears the value of the "redeem_code" field.
func (u *ExternalOrderFulfillmentUpsert) ClearRedeemCode() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldRedeemCode)
	return u
}

// SetRedeemType sets the "redeem_type" field.
func (u *ExternalOrderFulfillmentUpsert) SetRedeemType(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldRedeemType, v)
	return u
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateRedeemType() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldRedeemType)
	return u
}

// SetRedeemValue sets the "redeem_value" field.
func (u *ExternalOrderFulfillmentUpsert) SetRedeemValue(v float64) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldRedeemValue, v)
	return u
}

// UpdateRedeemValue sets the "redeem_value" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateRedeemValue() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldRedeemValue)
	return u
}

// AddRedeemValue adds v to the "redeem_value" field.
func (u *ExternalOrderFulfillmentUpsert) AddRedeemValue(v float64) *ExternalOrderFulfillmentUpsert {
	u.Add(externalorderfulfillment.FieldRedeemValue, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ExternalOrderFulfillmentUpsert) SetGroupID(v int64) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateGroupID() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ExternalOrderFulfillmentUpsert) AddGroupID(v int64) *ExternalOrderFulfillmentUpsert {
	u.Add(externalorderfulfillment.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ExternalOrderFulfillmentUpsert) ClearGroupID() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldGroupID)
	return u
}

// SetValidityDays sets the "validity_days" field.
func (u *ExternalOrderFulfillmentUpsert) SetValidityDays(v int) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldValidityDays, v)
	return u
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateValidityDays() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldValidityDays)
	return u
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ExternalOrderFulfillmentUpsert) AddValidityDays(v int) *ExternalOrderFulfillmentUpsert {
	u.Add(externalorderfulfillment.FieldValidityDays, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ExternalOrderFulfillmentUpsert) SetExpiresAt(v time.Time) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateExpiresAt() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ExternalOrderFulfillmentUpsert) ClearExpiresAt() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldExpiresAt)
	return u
}

// SetManualURL sets the "manual_url" field.
func (u *ExternalOrderFulfillmentUpsert) SetManualURL(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldManualURL, v)
	return u
}

// UpdateManualURL sets the "manual_url" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateManualURL() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldManualURL)
	return u
}

// ClearManualURL clears the value of the "manual_url" field.
func (u *ExternalOrderFulfillmentUpsert) ClearManualURL() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldManualURL)
	return u
}

// SetDeliveryMessage sets the "delivery_message" field.
func (u *ExternalOrderFulfillmentUpsert) SetDeliveryMessage(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldDeliveryMessage, v)
	return u
}

// UpdateDeliveryMessage sets the "delivery_message" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateDeliveryMessage() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldDeliveryMessage)
	return u
}

// ClearDeliveryMessage clears the value of the "delivery_message" field.
func (u *ExternalOrderFulfillmentUpsert) ClearDeliveryMessage() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldDeliveryMessage)
	return u
}

// SetStatus sets the "status" field.
func (u *ExternalOrderFulfillmentUpsert) SetStatus(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateStatus() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldStatus)
	return u
}

// SetNotifyStatus sets the "notify_status" field.
func (u *ExternalOrderFulfillmentUpsert) SetNotifyStatus(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldNotifyStatus, v)
	return u
}

// UpdateNotifyStatus sets the "notify_status" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateNotifyStatus() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldNotifyStatus)
	return u
}

// SetFailReason sets the "fail_reason" field.
func (u *ExternalOrderFulfillmentUpsert) SetFailReason(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldFailReason, v)
	return u
}

// UpdateFailReason sets the "fail_reason" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateFailReason() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldFailReason)
	return u
}

// ClearFailReason clears the value of the "fail_reason" field.
func (u *ExternalOrderFulfillmentUpsert) ClearFailReason() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldFailReason)
	return u
}

// SetOperator sets the "operator" field.
func (u *ExternalOrderFulfillmentUpsert) SetOperator(v string) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldOperator, v)
	return u
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateOperator() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldOperator)
	return u
}

// ClearOperator clears the value of the "operator" field.
func (u *ExternalOrderFulfillmentUpsert) ClearOperator() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldOperator)
	return u
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *ExternalOrderFulfillmentUpsert) SetDeliveredAt(v time.Time) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldDeliveredAt, v)
	return u
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateDeliveredAt() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldDeliveredAt)
	return u
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *ExternalOrderFulfillmentUpsert) ClearDeliveredAt() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldDeliveredAt)
	return u
}

// SetNotifiedAt sets the "notified_at" field.
func (u *ExternalOrderFulfillmentUpsert) SetNotifiedAt(v time.Time) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldNotifiedAt, v)
	return u
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateNotifiedAt() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldNotifiedAt)
	return u
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *ExternalOrderFulfillmentUpsert) ClearNotifiedAt() *ExternalOrderFulfillmentUpsert {
	u.SetNull(externalorderfulfillment.FieldNotifiedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalOrderFulfillmentUpsert) SetUpdatedAt(v time.Time) *ExternalOrderFulfillmentUpsert {
	u.Set(externalorderfulfillment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsert) UpdateUpdatedAt() *ExternalOrderFulfillmentUpsert {
	u.SetExcluded(externalorderfulfillment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ExternalOrderFulfillment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalOrderFulfillmentUpsertOne) UpdateNewValues() *ExternalOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(externalorderfulfillment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalOrderFulfillment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExternalOrderFulfillmentUpsertOne) Ignore() *ExternalOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalOrderFulfillmentUpsertOne) DoNothing() *ExternalOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalOrderFulfillmentCreate.OnConflict
// documentation for more info.
func (u *ExternalOrderFulfillmentUpsertOne) Update(set func(*ExternalOrderFulfillmentUpsert)) *ExternalOrderFulfillmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalOrderFulfillmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetPlatform(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdatePlatform() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformOrderID sets the "platform_order_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetPlatformOrderID(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetPlatformOrderID(v)
	})
}

// UpdatePlatformOrderID sets the "platform_order_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdatePlatformOrderID() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdatePlatformOrderID()
	})
}

// SetBuyerRef sets the "buyer_ref" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetBuyerRef(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetBuyerRef(v)
	})
}

// UpdateBuyerRef sets the "buyer_ref" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateBuyerRef() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateBuyerRef()
	})
}

// ClearBuyerRef clears the value of the "buyer_ref" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearBuyerRef() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearBuyerRef()
	})
}

// SetSkuCode sets the "sku_code" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetSkuCode(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetSkuCode(v)
	})
}

// UpdateSkuCode sets the "sku_code" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateSkuCode() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateSkuCode()
	})
}

// SetSkuName sets the "sku_name" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetSkuName(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetSkuName(v)
	})
}

// UpdateSkuName sets the "sku_name" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateSkuName() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateSkuName()
	})
}

// ClearSkuName clears the value of the "sku_name" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearSkuName() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearSkuName()
	})
}

// SetAmount sets the "amount" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetAmount(v float64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ExternalOrderFulfillmentUpsertOne) AddAmount(v float64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateAmount() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetCurrency(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateCurrency() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateCurrency()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetRedeemCodeID(v int64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) AddRedeemCodeID(v int64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateRedeemCodeID() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearRedeemCodeID() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetRedeemCode sets the "redeem_code" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetRedeemCode(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemCode(v)
	})
}

// UpdateRedeemCode sets the "redeem_code" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateRedeemCode() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemCode()
	})
}

// ClearRedeemCode clears the value of the "redeem_code" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearRedeemCode() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearRedeemCode()
	})
}

// SetRedeemType sets the "redeem_type" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetRedeemType(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemType(v)
	})
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateRedeemType() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemType()
	})
}

// SetRedeemValue sets the "redeem_value" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetRedeemValue(v float64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemValue(v)
	})
}

// AddRedeemValue adds v to the "redeem_value" field.
func (u *ExternalOrderFulfillmentUpsertOne) AddRedeemValue(v float64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddRedeemValue(v)
	})
}

// UpdateRedeemValue sets the "redeem_value" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateRedeemValue() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemValue()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetGroupID(v int64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) AddGroupID(v int64) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateGroupID() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearGroupID() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetValidityDays(v int) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ExternalOrderFulfillmentUpsertOne) AddValidityDays(v int) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateValidityDays() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateValidityDays()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetExpiresAt(v time.Time) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateExpiresAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearExpiresAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearExpiresAt()
	})
}

// SetManualURL sets the "manual_url" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetManualURL(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetManualURL(v)
	})
}

// UpdateManualURL sets the "manual_url" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateManualURL() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateManualURL()
	})
}

// ClearManualURL clears the value of the "manual_url" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearManualURL() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearManualURL()
	})
}

// SetDeliveryMessage sets the "delivery_message" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetDeliveryMessage(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetDeliveryMessage(v)
	})
}

// UpdateDeliveryMessage sets the "delivery_message" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateDeliveryMessage() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateDeliveryMessage()
	})
}

// ClearDeliveryMessage clears the value of the "delivery_message" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearDeliveryMessage() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearDeliveryMessage()
	})
}

// SetStatus sets the "status" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetStatus(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateStatus() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateStatus()
	})
}

// SetNotifyStatus sets the "notify_status" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetNotifyStatus(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetNotifyStatus(v)
	})
}

// UpdateNotifyStatus sets the "notify_status" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateNotifyStatus() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateNotifyStatus()
	})
}

// SetFailReason sets the "fail_reason" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetFailReason(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetFailReason(v)
	})
}

// UpdateFailReason sets the "fail_reason" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateFailReason() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateFailReason()
	})
}

// ClearFailReason clears the value of the "fail_reason" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearFailReason() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearFailReason()
	})
}

// SetOperator sets the "operator" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetOperator(v string) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetOperator(v)
	})
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateOperator() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateOperator()
	})
}

// ClearOperator clears the value of the "operator" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearOperator() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearOperator()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetDeliveredAt(v time.Time) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateDeliveredAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateDeliveredAt()
	})
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearDeliveredAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearDeliveredAt()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetNotifiedAt(v time.Time) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateNotifiedAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) ClearNotifiedAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearNotifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalOrderFulfillmentUpsertOne) SetUpdatedAt(v time.Time) *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertOne) UpdateUpdatedAt() *ExternalOrderFulfillmentUpsertOne {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExternalOrderFulfillmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalOrderFulfillmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalOrderFulfillmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExternalOrderFulfillmentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExternalOrderFulfillmentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExternalOrderFulfillmentCreateBulk is the builder for creating many ExternalOrderFulfillment entities in bulk.
type ExternalOrderFulfillmentCreateBulk struct {
	config
	err      error
	builders []*ExternalOrderFulfillmentCreate
	conflict []sql.ConflictOption
}

// Save creates the ExternalOrderFulfillment entities in the database.
func (_c *ExternalOrderFulfillmentCreateBulk) Save(ctx context.Context) ([]*ExternalOrderFulfillment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExternalOrderFulfillment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExternalOrderFulfillmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExternalOrderFulfillmentCreateBulk) SaveX(ctx context.Context) []*ExternalOrderFulfillment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalOrderFulfillmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalOrderFulfillmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalOrderFulfillment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalOrderFulfillmentUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *ExternalOrderFulfillmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExternalOrderFulfillmentUpsertBulk {
	_c.conflict = opts
	return &ExternalOrderFulfillmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalOrderFulfillment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExternalOrderFulfillmentCreateBulk) OnConflictColumns(columns ...string) *ExternalOrderFulfillmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExternalOrderFulfillmentUpsertBulk{
		create: _c,
	}
}

// ExternalOrderFulfillmentUpsertBulk is the builder for "upsert"-ing
// a bulk of ExternalOrderFulfillment nodes.
type ExternalOrderFulfillmentUpsertBulk struct {
	create *ExternalOrderFulfillmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExternalOrderFulfillment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateNewValues() *ExternalOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(externalorderfulfillment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalOrderFulfillment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExternalOrderFulfillmentUpsertBulk) Ignore() *ExternalOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalOrderFulfillmentUpsertBulk) DoNothing() *ExternalOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalOrderFulfillmentCreateBulk.OnConflict
// documentation for more info.
func (u *ExternalOrderFulfillmentUpsertBulk) Update(set func(*ExternalOrderFulfillmentUpsert)) *ExternalOrderFulfillmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalOrderFulfillmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetPlatform(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdatePlatform() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformOrderID sets the "platform_order_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetPlatformOrderID(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetPlatformOrderID(v)
	})
}

// UpdatePlatformOrderID sets the "platform_order_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdatePlatformOrderID() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdatePlatformOrderID()
	})
}

// SetBuyerRef sets the "buyer_ref" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetBuyerRef(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetBuyerRef(v)
	})
}

// UpdateBuyerRef sets the "buyer_ref" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateBuyerRef() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateBuyerRef()
	})
}

// ClearBuyerRef clears the value of the "buyer_ref" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearBuyerRef() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearBuyerRef()
	})
}

// SetSkuCode sets the "sku_code" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetSkuCode(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetSkuCode(v)
	})
}

// UpdateSkuCode sets the "sku_code" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateSkuCode() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateSkuCode()
	})
}

// SetSkuName sets the "sku_name" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetSkuName(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetSkuName(v)
	})
}

// UpdateSkuName sets the "sku_name" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateSkuName() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateSkuName()
	})
}

// ClearSkuName clears the value of the "sku_name" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearSkuName() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearSkuName()
	})
}

// SetAmount sets the "amount" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetAmount(v float64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *ExternalOrderFulfillmentUpsertBulk) AddAmount(v float64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateAmount() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetCurrency(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateCurrency() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateCurrency()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetRedeemCodeID(v int64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) AddRedeemCodeID(v int64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateRedeemCodeID() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearRedeemCodeID() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetRedeemCode sets the "redeem_code" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetRedeemCode(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemCode(v)
	})
}

// UpdateRedeemCode sets the "redeem_code" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateRedeemCode() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemCode()
	})
}

// ClearRedeemCode clears the value of the "redeem_code" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearRedeemCode() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearRedeemCode()
	})
}

// SetRedeemType sets the "redeem_type" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetRedeemType(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemType(v)
	})
}

// UpdateRedeemType sets the "redeem_type" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateRedeemType() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemType()
	})
}

// SetRedeemValue sets the "redeem_value" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetRedeemValue(v float64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetRedeemValue(v)
	})
}

// AddRedeemValue adds v to the "redeem_value" field.
func (u *ExternalOrderFulfillmentUpsertBulk) AddRedeemValue(v float64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddRedeemValue(v)
	})
}

// UpdateRedeemValue sets the "redeem_value" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateRedeemValue() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateRedeemValue()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetGroupID(v int64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) AddGroupID(v int64) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateGroupID() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearGroupID() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearGroupID()
	})
}

// SetValidityDays sets the "validity_days" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetValidityDays(v int) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetValidityDays(v)
	})
}

// AddValidityDays adds v to the "validity_days" field.
func (u *ExternalOrderFulfillmentUpsertBulk) AddValidityDays(v int) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.AddValidityDays(v)
	})
}

// UpdateValidityDays sets the "validity_days" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateValidityDays() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateValidityDays()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetExpiresAt(v time.Time) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateExpiresAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearExpiresAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearExpiresAt()
	})
}

// SetManualURL sets the "manual_url" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetManualURL(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetManualURL(v)
	})
}

// UpdateManualURL sets the "manual_url" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateManualURL() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateManualURL()
	})
}

// ClearManualURL clears the value of the "manual_url" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearManualURL() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearManualURL()
	})
}

// SetDeliveryMessage sets the "delivery_message" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetDeliveryMessage(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetDeliveryMessage(v)
	})
}

// UpdateDeliveryMessage sets the "delivery_message" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateDeliveryMessage() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateDeliveryMessage()
	})
}

// ClearDeliveryMessage clears the value of the "delivery_message" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearDeliveryMessage() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearDeliveryMessage()
	})
}

// SetStatus sets the "status" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetStatus(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateStatus() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateStatus()
	})
}

// SetNotifyStatus sets the "notify_status" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetNotifyStatus(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetNotifyStatus(v)
	})
}

// UpdateNotifyStatus sets the "notify_status" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateNotifyStatus() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateNotifyStatus()
	})
}

// SetFailReason sets the "fail_reason" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetFailReason(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetFailReason(v)
	})
}

// UpdateFailReason sets the "fail_reason" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateFailReason() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateFailReason()
	})
}

// ClearFailReason clears the value of the "fail_reason" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearFailReason() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearFailReason()
	})
}

// SetOperator sets the "operator" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetOperator(v string) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetOperator(v)
	})
}

// UpdateOperator sets the "operator" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateOperator() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateOperator()
	})
}

// ClearOperator clears the value of the "operator" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearOperator() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearOperator()
	})
}

// SetDeliveredAt sets the "delivered_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetDeliveredAt(v time.Time) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetDeliveredAt(v)
	})
}

// UpdateDeliveredAt sets the "delivered_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateDeliveredAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateDeliveredAt()
	})
}

// ClearDeliveredAt clears the value of the "delivered_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearDeliveredAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearDeliveredAt()
	})
}

// SetNotifiedAt sets the "notified_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetNotifiedAt(v time.Time) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetNotifiedAt(v)
	})
}

// UpdateNotifiedAt sets the "notified_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateNotifiedAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateNotifiedAt()
	})
}

// ClearNotifiedAt clears the value of the "notified_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) ClearNotifiedAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.ClearNotifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalOrderFulfillmentUpsertBulk) SetUpdatedAt(v time.Time) *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalOrderFulfillmentUpsertBulk) UpdateUpdatedAt() *ExternalOrderFulfillmentUpsertBulk {
	return u.Update(func(s *ExternalOrderFulfillmentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExternalOrderFulfillmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExternalOrderFulfillmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalOrderFulfillmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalOrderFulfillmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
