// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalorderfulfillment"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ExternalOrderFulfillmentDelete is the builder for deleting a ExternalOrderFulfillment entity.
type ExternalOrderFulfillmentDelete struct {
	config
	hooks    []Hook
	mutation *ExternalOrderFulfillmentMutation
}

// Where appends a list predicates to the ExternalOrderFulfillmentDelete builder.
func (_d *ExternalOrderFulfillmentDelete) Where(ps ...predicate.ExternalOrderFulfillment) *ExternalOrderFulfillmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExternalOrderFulfillmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalOrderFulfillmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExternalOrderFulfillmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externalorderfulfillment.Table, sqlgraph.NewFieldSpec(externalorderfulfillment.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExternalOrderFulfillmentDeleteOne is the builder for deleting a single ExternalOrderFulfillment entity.
type ExternalOrderFulfillmentDeleteOne struct {
	_d *ExternalOrderFulfillmentDelete
}

// Where appends a list predicates to the ExternalOrderFulfillmentDelete builder.
func (_d *ExternalOrderFulfillmentDeleteOne) Where(ps ...predicate.ExternalOrderFulfillment) *ExternalOrderFulfillmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExternalOrderFulfillmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalorderfulfillment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalOrderFulfillmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
