// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UsageLog is the model entity for the UsageLog schema.
type UsageLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel *string `json:"requested_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel *string `json:"upstream_model,omitempty"`
	// 渠道 ID
	ChannelID *int64 `json:"channel_id,omitempty"`
	// 模型映射链
	ModelMappingChain *string `json:"model_mapping_chain,omitempty"`
	// 计费层级标签
	BillingTier *string `json:"billing_tier,omitempty"`
	// 计费模式：token/per_request/image
	BillingMode *string `json:"billing_mode,omitempty"`
	// PromptCacheKeyHash holds the value of the "prompt_cache_key_hash" field.
	PromptCacheKeyHash *string `json:"prompt_cache_key_hash,omitempty"`
	// PromptCacheKeySource holds the value of the "prompt_cache_key_source" field.
	PromptCacheKeySource *string `json:"prompt_cache_key_source,omitempty"`
	// PromptCachePrefixHash holds the value of the "prompt_cache_prefix_hash" field.
	PromptCachePrefixHash *string `json:"prompt_cache_prefix_hash,omitempty"`
	// PromptCacheToolsHash holds the value of the "prompt_cache_tools_hash" field.
	PromptCacheToolsHash *string `json:"prompt_cache_tools_hash,omitempty"`
	// PromptCacheSystemHash holds the value of the "prompt_cache_system_hash" field.
	PromptCacheSystemHash *string `json:"prompt_cache_system_hash,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// CacheCreationTokens holds the value of the "cache_creation_tokens" field.
	CacheCreationTokens int `json:"cache_creation_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	// CacheCreation5mTokens holds the value of the "cache_creation_5m_tokens" field.
	CacheCreation5mTokens int `json:"cache_creation_5m_tokens,omitempty"`
	// CacheCreation1hTokens holds the value of the "cache_creation_1h_tokens" field.
	CacheCreation1hTokens int `json:"cache_creation_1h_tokens,omitempty"`
	// InputCost holds the value of the "input_cost" field.
	InputCost float64 `json:"input_cost,omitempty"`
	// OutputCost holds the value of the "output_cost" field.
	OutputCost float64 `json:"output_cost,omitempty"`
	// CacheCreationCost holds the value of the "cache_creation_cost" field.
	CacheCreationCost float64 `json:"cache_creation_cost,omitempty"`
	// CacheReadCost holds the value of the "cache_read_cost" field.
	CacheReadCost float64 `json:"cache_read_cost,omitempty"`
	// TotalCost holds the value of the "total_cost" field.
	TotalCost float64 `json:"total_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// RateMultiplier holds the value of the "rate_multiplier" field.
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// Whether long-context pricing changed token prices for this request
	LongContextBillingApplied bool `json:"long_context_billing_applied,omitempty"`
	// AccountRateMultiplier holds the value of the "account_rate_multiplier" field.
	AccountRateMultiplier *float64 `json:"account_rate_multiplier,omitempty"`
	// BillingType holds the value of the "billing_type" field.
	BillingType int8 `json:"billing_type,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int `json:"duration_ms,omitempty"`
	// FirstTokenMs holds the value of the "first_token_ms" field.
	FirstTokenMs *int `json:"first_token_ms,omitempty"`
	// ClientTransport holds the value of the "client_transport" field.
	ClientTransport *string `json:"client_transport,omitempty"`
	// AuthLatencyMs holds the value of the "auth_latency_ms" field.
	AuthLatencyMs *int `json:"auth_latency_ms,omitempty"`
	// RoutingLatencyMs holds the value of the "routing_latency_ms" field.
	RoutingLatencyMs *int `json:"routing_latency_ms,omitempty"`
	// UpstreamLatencyMs holds the value of the "upstream_latency_ms" field.
	UpstreamLatencyMs *int `json:"upstream_latency_ms,omitempty"`
	// ResponseLatencyMs holds the value of the "response_latency_ms" field.
	ResponseLatencyMs *int `json:"response_latency_ms,omitempty"`
	// RequestStartedAt holds the value of the "request_started_at" field.
	RequestStartedAt *time.Time `json:"request_started_at,omitempty"`
	// RequestTotalMs holds the value of the "request_total_ms" field.
	RequestTotalMs *int `json:"request_total_ms,omitempty"`
	// RequestBodyReadMs holds the value of the "request_body_read_ms" field.
	RequestBodyReadMs *int `json:"request_body_read_ms,omitempty"`
	// RequestBodyBytes holds the value of the "request_body_bytes" field.
	RequestBodyBytes *int64 `json:"request_body_bytes,omitempty"`
	// UpstreamConnectionReused holds the value of the "upstream_connection_reused" field.
	UpstreamConnectionReused *bool `json:"upstream_connection_reused,omitempty"`
	// UpstreamConnectionReadyMs holds the value of the "upstream_connection_ready_ms" field.
	UpstreamConnectionReadyMs *int `json:"upstream_connection_ready_ms,omitempty"`
	// UpstreamDNSLookupMs holds the value of the "upstream_dns_lookup_ms" field.
	UpstreamDNSLookupMs *int `json:"upstream_dns_lookup_ms,omitempty"`
	// UpstreamTCPConnectMs holds the value of the "upstream_tcp_connect_ms" field.
	UpstreamTCPConnectMs *int `json:"upstream_tcp_connect_ms,omitempty"`
	// UpstreamTLSHandshakeMs holds the value of the "upstream_tls_handshake_ms" field.
	UpstreamTLSHandshakeMs *int `json:"upstream_tls_handshake_ms,omitempty"`
	// UpstreamRequestHeadersWrittenMs holds the value of the "upstream_request_headers_written_ms" field.
	UpstreamRequestHeadersWrittenMs *int `json:"upstream_request_headers_written_ms,omitempty"`
	// UpstreamRequestWrittenMs holds the value of the "upstream_request_written_ms" field.
	UpstreamRequestWrittenMs *int `json:"upstream_request_written_ms,omitempty"`
	// UpstreamFirstByteMs holds the value of the "upstream_first_byte_ms" field.
	UpstreamFirstByteMs *int `json:"upstream_first_byte_ms,omitempty"`
	// UpstreamResponseHeadersReceivedMs holds the value of the "upstream_response_headers_received_ms" field.
	UpstreamResponseHeadersReceivedMs *int `json:"upstream_response_headers_received_ms,omitempty"`
	// UpstreamResponseBodyFirstByteMs holds the value of the "upstream_response_body_first_byte_ms" field.
	UpstreamResponseBodyFirstByteMs *int `json:"upstream_response_body_first_byte_ms,omitempty"`
	// UpstreamFirstEventMs holds the value of the "upstream_first_event_ms" field.
	UpstreamFirstEventMs *int `json:"upstream_first_event_ms,omitempty"`
	// RequestFirstOutputCharacterMs holds the value of the "request_first_output_character_ms" field.
	RequestFirstOutputCharacterMs *int `json:"request_first_output_character_ms,omitempty"`
	// RequestFirstTokenMs holds the value of the "request_first_token_ms" field.
	RequestFirstTokenMs *int `json:"request_first_token_ms,omitempty"`
	// RouteKind holds the value of the "route_kind" field.
	RouteKind *string `json:"route_kind,omitempty"`
	// ProxyIDSnapshot holds the value of the "proxy_id_snapshot" field.
	ProxyIDSnapshot *int64 `json:"proxy_id_snapshot,omitempty"`
	// ProxyNameSnapshot holds the value of the "proxy_name_snapshot" field.
	ProxyNameSnapshot *string `json:"proxy_name_snapshot,omitempty"`
	// ProxyProtocolSnapshot holds the value of the "proxy_protocol_snapshot" field.
	ProxyProtocolSnapshot *string `json:"proxy_protocol_snapshot,omitempty"`
	// RouteFingerprint holds the value of the "route_fingerprint" field.
	RouteFingerprint *string `json:"route_fingerprint,omitempty"`
	// FinalUpstreamStatus holds the value of the "final_upstream_status" field.
	FinalUpstreamStatus *int `json:"final_upstream_status,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// AccountSwitchCount holds the value of the "account_switch_count" field.
	AccountSwitchCount int `json:"account_switch_count,omitempty"`
	// AttemptTimeline holds the value of the "attempt_timeline" field.
	AttemptTimeline []map[string]interface{} `json:"attempt_timeline,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent *string `json:"user_agent,omitempty"`
	// IPAddress holds the value of the "ip_address" field.
	IPAddress *string `json:"ip_address,omitempty"`
	// ImageCount holds the value of the "image_count" field.
	ImageCount int `json:"image_count,omitempty"`
	// ImageSize holds the value of the "image_size" field.
	ImageSize *string `json:"image_size,omitempty"`
	// ImageInputSize holds the value of the "image_input_size" field.
	ImageInputSize *string `json:"image_input_size,omitempty"`
	// ImageOutputSize holds the value of the "image_output_size" field.
	ImageOutputSize *string `json:"image_output_size,omitempty"`
	// ImageSizeSource holds the value of the "image_size_source" field.
	ImageSizeSource *string `json:"image_size_source,omitempty"`
	// ImageSizeBreakdown holds the value of the "image_size_breakdown" field.
	ImageSizeBreakdown map[string]int `json:"image_size_breakdown,omitempty"`
	// 视频生成数量；>0 表示本行是视频生成用量
	VideoCount int `json:"video_count,omitempty"`
	// 计费用视频分辨率 480p/720p/1080p
	VideoResolution *string `json:"video_resolution,omitempty"`
	// 提交时请求的视频时长（秒），按秒计费的乘数
	VideoDurationSeconds *int `json:"video_duration_seconds,omitempty"`
	// CacheTTLOverridden holds the value of the "cache_ttl_overridden" field.
	CacheTTLOverridden bool `json:"cache_ttl_overridden,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageLogQuery when eager-loading is set.
	Edges        UsageLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageLogEdges holds the relations/edges for other nodes in the graph.
type UsageLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldAttemptTimeline, usagelog.FieldImageSizeBreakdown:
			values[i] = new([]byte)
		case usagelog.FieldLongContextBillingApplied, usagelog.FieldStream, usagelog.FieldUpstreamConnectionReused, usagelog.FieldCacheTTLOverridden:
			values[i] = new(sql.NullBool)
		case usagelog.FieldInputCost, usagelog.FieldOutputCost, usagelog.FieldCacheCreationCost, usagelog.FieldCacheReadCost, usagelog.FieldTotalCost, usagelog.FieldActualCost, usagelog.FieldRateMultiplier, usagelog.FieldAccountRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case usagelog.FieldID, usagelog.FieldUserID, usagelog.FieldAPIKeyID, usagelog.FieldAccountID, usagelog.FieldChannelID, usagelog.FieldGroupID, usagelog.FieldSubscriptionID, usagelog.FieldInputTokens, usagelog.FieldOutputTokens, usagelog.FieldCacheCreationTokens, usagelog.FieldCacheReadTokens, usagelog.FieldCacheCreation5mTokens, usagelog.FieldCacheCreation1hTokens, usagelog.FieldBillingType, usagelog.FieldDurationMs, usagelog.FieldFirstTokenMs, usagelog.FieldAuthLatencyMs, usagelog.FieldRoutingLatencyMs, usagelog.FieldUpstreamLatencyMs, usagelog.FieldResponseLatencyMs, usagelog.FieldRequestTotalMs, usagelog.FieldRequestBodyReadMs, usagelog.FieldRequestBodyBytes, usagelog.FieldUpstreamConnectionReadyMs, usagelog.FieldUpstreamDNSLookupMs, usagelog.FieldUpstreamTCPConnectMs, usagelog.FieldUpstreamTLSHandshakeMs, usagelog.FieldUpstreamRequestHeadersWrittenMs, usagelog.FieldUpstreamRequestWrittenMs, usagelog.FieldUpstreamFirstByteMs, usagelog.FieldUpstreamResponseHeadersReceivedMs, usagelog.FieldUpstreamResponseBodyFirstByteMs, usagelog.FieldUpstreamFirstEventMs, usagelog.FieldRequestFirstOutputCharacterMs, usagelog.FieldRequestFirstTokenMs, usagelog.FieldProxyIDSnapshot, usagelog.FieldFinalUpstreamStatus, usagelog.FieldRetryCount, usagelog.FieldAccountSwitchCount, usagelog.FieldImageCount, usagelog.FieldVideoCount, usagelog.FieldVideoDurationSeconds:
			values[i] = new(sql.NullInt64)
		case usagelog.FieldRequestID, usagelog.FieldModel, usagelog.FieldRequestedModel, usagelog.FieldUpstreamModel, usagelog.FieldModelMappingChain, usagelog.FieldBillingTier, usagelog.FieldBillingMode, usagelog.FieldPromptCacheKeyHash, usagelog.FieldPromptCacheKeySource, usagelog.FieldPromptCachePrefixHash, usagelog.FieldPromptCacheToolsHash, usagelog.FieldPromptCacheSystemHash, usagelog.FieldClientTransport, usagelog.FieldRouteKind, usagelog.FieldProxyNameSnapshot, usagelog.FieldProxyProtocolSnapshot, usagelog.FieldRouteFingerprint, usagelog.FieldUserAgent, usagelog.FieldIPAddress, usagelog.FieldImageSize, usagelog.FieldImageInputSize, usagelog.FieldImageOutputSize, usagelog.FieldImageSizeSource, usagelog.FieldVideoResolution:
			values[i] = new(sql.NullString)
		case usagelog.FieldRequestStartedAt, usagelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLog fields.
func (_m *UsageLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagelog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usagelog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case usagelog.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case usagelog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case usagelog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case usagelog.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = new(string)
				*_m.RequestedModel = value.String
			}
		case usagelog.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = new(string)
				*_m.UpstreamModel = value.String
			}
		case usagelog.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int64)
				*_m.ChannelID = value.Int64
			}
		case usagelog.FieldModelMappingChain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_mapping_chain", values[i])
			} else if value.Valid {
				_m.ModelMappingChain = new(string)
				*_m.ModelMappingChain = value.String
			}
		case usagelog.FieldBillingTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_tier", values[i])
			} else if value.Valid {
				_m.BillingTier = new(string)
				*_m.BillingTier = value.String
			}
		case usagelog.FieldBillingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_mode", values[i])
			} else if value.Valid {
				_m.BillingMode = new(string)
				*_m.BillingMode = value.String
			}
		case usagelog.FieldPromptCacheKeyHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_cache_key_hash", values[i])
			} else if value.Valid {
				_m.PromptCacheKeyHash = new(string)
				*_m.PromptCacheKeyHash = value.String
			}
		case usagelog.FieldPromptCacheKeySource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_cache_key_source", values[i])
			} else if value.Valid {
				_m.PromptCacheKeySource = new(string)
				*_m.PromptCacheKeySource = value.String
			}
		case usagelog.FieldPromptCachePrefixHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_cache_prefix_hash", values[i])
			} else if value.Valid {
				_m.PromptCachePrefixHash = new(string)
				*_m.PromptCachePrefixHash = value.String
			}
		case usagelog.FieldPromptCacheToolsHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_cache_tools_hash", values[i])
			} else if value.Valid {
				_m.PromptCacheToolsHash = new(string)
				*_m.PromptCacheToolsHash = value.String
			}
		case usagelog.FieldPromptCacheSystemHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_cache_system_hash", values[i])
			} else if value.Valid {
				_m.PromptCacheSystemHash = new(string)
				*_m.PromptCacheSystemHash = value.String
			}
		case usagelog.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case usagelog.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case usagelog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case usagelog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case usagelog.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = int(value.Int64)
			}
		case usagelog.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = int(value.Int64)
			}
		case usagelog.FieldCacheCreation5mTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_5m_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation5mTokens = int(value.Int64)
			}
		case usagelog.FieldCacheCreation1hTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_1h_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreation1hTokens = int(value.Int64)
			}
		case usagelog.FieldInputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_cost", values[i])
			} else if value.Valid {
				_m.InputCost = value.Float64
			}
		case usagelog.FieldOutputCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_cost", values[i])
			} else if value.Valid {
				_m.OutputCost = value.Float64
			}
		case usagelog.FieldCacheCreationCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_cost", values[i])
			} else if value.Valid {
				_m.CacheCreationCost = value.Float64
			}
		case usagelog.FieldCacheReadCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_cost", values[i])
			} else if value.Valid {
				_m.CacheReadCost = value.Float64
			}
		case usagelog.FieldTotalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost", values[i])
			} else if value.Valid {
				_m.TotalCost = value.Float64
			}
		case usagelog.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case usagelog.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case usagelog.FieldLongContextBillingApplied:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field long_context_billing_applied", values[i])
			} else if value.Valid {
				_m.LongContextBillingApplied = value.Bool
			}
		case usagelog.FieldAccountRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_rate_multiplier", values[i])
			} else if value.Valid {
				_m.AccountRateMultiplier = new(float64)
				*_m.AccountRateMultiplier = value.Float64
			}
		case usagelog.FieldBillingType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = int8(value.Int64)
			}
		case usagelog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				_m.Stream = value.Bool
			}
		case usagelog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case usagelog.FieldFirstTokenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_ms", values[i])
			} else if value.Valid {
				_m.FirstTokenMs = new(int)
				*_m.FirstTokenMs = int(value.Int64)
			}
		case usagelog.FieldClientTransport:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_transport", values[i])
			} else if value.Valid {
				_m.ClientTransport = new(string)
				*_m.ClientTransport = value.String
			}
		case usagelog.FieldAuthLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field auth_latency_ms", values[i])
			} else if value.Valid {
				_m.AuthLatencyMs = new(int)
				*_m.AuthLatencyMs = int(value.Int64)
			}
		case usagelog.FieldRoutingLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field routing_latency_ms", values[i])
			} else if value.Valid {
				_m.RoutingLatencyMs = new(int)
				*_m.RoutingLatencyMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_latency_ms", values[i])
			} else if value.Valid {
				_m.UpstreamLatencyMs = new(int)
				*_m.UpstreamLatencyMs = int(value.Int64)
			}
		case usagelog.FieldResponseLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_latency_ms", values[i])
			} else if value.Valid {
				_m.ResponseLatencyMs = new(int)
				*_m.ResponseLatencyMs = int(value.Int64)
			}
		case usagelog.FieldRequestStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field request_started_at", values[i])
			} else if value.Valid {
				_m.RequestStartedAt = new(time.Time)
				*_m.RequestStartedAt = value.Time
			}
		case usagelog.FieldRequestTotalMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_total_ms", values[i])
			} else if value.Valid {
				_m.RequestTotalMs = new(int)
				*_m.RequestTotalMs = int(value.Int64)
			}
		case usagelog.FieldRequestBodyReadMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_read_ms", values[i])
			} else if value.Valid {
				_m.RequestBodyReadMs = new(int)
				*_m.RequestBodyReadMs = int(value.Int64)
			}
		case usagelog.FieldRequestBodyBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_body_bytes", values[i])
			} else if value.Valid {
				_m.RequestBodyBytes = new(int64)
				*_m.RequestBodyBytes = value.Int64
			}
		case usagelog.FieldUpstreamConnectionReused:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_connection_reused", values[i])
			} else if value.Valid {
				_m.UpstreamConnectionReused = new(bool)
				*_m.UpstreamConnectionReused = value.Bool
			}
		case usagelog.FieldUpstreamConnectionReadyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_connection_ready_ms", values[i])
			} else if value.Valid {
				_m.UpstreamConnectionReadyMs = new(int)
				*_m.UpstreamConnectionReadyMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamDNSLookupMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_dns_lookup_ms", values[i])
			} else if value.Valid {
				_m.UpstreamDNSLookupMs = new(int)
				*_m.UpstreamDNSLookupMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamTCPConnectMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_tcp_connect_ms", values[i])
			} else if value.Valid {
				_m.UpstreamTCPConnectMs = new(int)
				*_m.UpstreamTCPConnectMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamTLSHandshakeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_tls_handshake_ms", values[i])
			} else if value.Valid {
				_m.UpstreamTLSHandshakeMs = new(int)
				*_m.UpstreamTLSHandshakeMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamRequestHeadersWrittenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_headers_written_ms", values[i])
			} else if value.Valid {
				_m.UpstreamRequestHeadersWrittenMs = new(int)
				*_m.UpstreamRequestHeadersWrittenMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamRequestWrittenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_written_ms", values[i])
			} else if value.Valid {
				_m.UpstreamRequestWrittenMs = new(int)
				*_m.UpstreamRequestWrittenMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamFirstByteMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_first_byte_ms", values[i])
			} else if value.Valid {
				_m.UpstreamFirstByteMs = new(int)
				*_m.UpstreamFirstByteMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamResponseHeadersReceivedMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_headers_received_ms", values[i])
			} else if value.Valid {
				_m.UpstreamResponseHeadersReceivedMs = new(int)
				*_m.UpstreamResponseHeadersReceivedMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamResponseBodyFirstByteMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_response_body_first_byte_ms", values[i])
			} else if value.Valid {
				_m.UpstreamResponseBodyFirstByteMs = new(int)
				*_m.UpstreamResponseBodyFirstByteMs = int(value.Int64)
			}
		case usagelog.FieldUpstreamFirstEventMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_first_event_ms", values[i])
			} else if value.Valid {
				_m.UpstreamFirstEventMs = new(int)
				*_m.UpstreamFirstEventMs = int(value.Int64)
			}
		case usagelog.FieldRequestFirstOutputCharacterMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_first_output_character_ms", values[i])
			} else if value.Valid {
				_m.RequestFirstOutputCharacterMs = new(int)
				*_m.RequestFirstOutputCharacterMs = int(value.Int64)
			}
		case usagelog.FieldRequestFirstTokenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_first_token_ms", values[i])
			} else if value.Valid {
				_m.RequestFirstTokenMs = new(int)
				*_m.RequestFirstTokenMs = int(value.Int64)
			}
		case usagelog.FieldRouteKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_kind", values[i])
			} else if value.Valid {
				_m.RouteKind = new(string)
				*_m.RouteKind = value.String
			}
		case usagelog.FieldProxyIDSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id_snapshot", values[i])
			} else if value.Valid {
				_m.ProxyIDSnapshot = new(int64)
				*_m.ProxyIDSnapshot = value.Int64
			}
		case usagelog.FieldProxyNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_name_snapshot", values[i])
			} else if value.Valid {
				_m.ProxyNameSnapshot = new(string)
				*_m.ProxyNameSnapshot = value.String
			}
		case usagelog.FieldProxyProtocolSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_protocol_snapshot", values[i])
			} else if value.Valid {
				_m.ProxyProtocolSnapshot = new(string)
				*_m.ProxyProtocolSnapshot = value.String
			}
		case usagelog.FieldRouteFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_fingerprint", values[i])
			} else if value.Valid {
				_m.RouteFingerprint = new(string)
				*_m.RouteFingerprint = value.String
			}
		case usagelog.FieldFinalUpstreamStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field final_upstream_status", values[i])
			} else if value.Valid {
				_m.FinalUpstreamStatus = new(int)
				*_m.FinalUpstreamStatus = int(value.Int64)
			}
		case usagelog.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case usagelog.FieldAccountSwitchCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_switch_count", values[i])
			} else if value.Valid {
				_m.AccountSwitchCount = int(value.Int64)
			}
		case usagelog.FieldAttemptTimeline:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_timeline", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AttemptTimeline); err != nil {
					return fmt.Errorf("unmarshal field attempt_timeline: %w", err)
				}
			}
		case usagelog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case usagelog.FieldIPAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_address", values[i])
			} else if value.Valid {
				_m.IPAddress = new(string)
				*_m.IPAddress = value.String
			}
		case usagelog.FieldImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field image_count", values[i])
			} else if value.Valid {
				_m.ImageCount = int(value.Int64)
			}
		case usagelog.FieldImageSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size", values[i])
			} else if value.Valid {
				_m.ImageSize = new(string)
				*_m.ImageSize = value.String
			}
		case usagelog.FieldImageInputSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_input_size", values[i])
			} else if value.Valid {
				_m.ImageInputSize = new(string)
				*_m.ImageInputSize = value.String
			}
		case usagelog.FieldImageOutputSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_output_size", values[i])
			} else if value.Valid {
				_m.ImageOutputSize = new(string)
				*_m.ImageOutputSize = value.String
			}
		case usagelog.FieldImageSizeSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size_source", values[i])
			} else if value.Valid {
				_m.ImageSizeSource = new(string)
				*_m.ImageSizeSource = value.String
			}
		case usagelog.FieldImageSizeBreakdown:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field image_size_breakdown", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ImageSizeBreakdown); err != nil {
					return fmt.Errorf("unmarshal field image_size_breakdown: %w", err)
				}
			}
		case usagelog.FieldVideoCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_count", values[i])
			} else if value.Valid {
				_m.VideoCount = int(value.Int64)
			}
		case usagelog.FieldVideoResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field video_resolution", values[i])
			} else if value.Valid {
				_m.VideoResolution = new(string)
				*_m.VideoResolution = value.String
			}
		case usagelog.FieldVideoDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field video_duration_seconds", values[i])
			} else if value.Valid {
				_m.VideoDurationSeconds = new(int)
				*_m.VideoDurationSeconds = int(value.Int64)
			}
		case usagelog.FieldCacheTTLOverridden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cache_ttl_overridden", values[i])
			} else if value.Valid {
				_m.CacheTTLOverridden = value.Bool
			}
		case usagelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLog.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UsageLog entity.
func (_m *UsageLog) QueryUser() *UserQuery {
	return NewUsageLogClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the UsageLog entity.
func (_m *UsageLog) QueryAPIKey() *APIKeyQuery {
	return NewUsageLogClient(_m.config).QueryAPIKey(_m)
}

// QueryAccount queries the "account" edge of the UsageLog entity.
func (_m *UsageLog) QueryAccount() *AccountQuery {
	return NewUsageLogClient(_m.config).QueryAccount(_m)
}

// QueryGroup queries the "group" edge of the UsageLog entity.
func (_m *UsageLog) QueryGroup() *GroupQuery {
	return NewUsageLogClient(_m.config).QueryGroup(_m)
}

// QuerySubscription queries the "subscription" edge of the UsageLog entity.
func (_m *UsageLog) QuerySubscription() *UserSubscriptionQuery {
	return NewUsageLogClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this UsageLog.
// Note that you need to call UsageLog.Unwrap() before calling this method if this UsageLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLog) Update() *UsageLogUpdateOne {
	return NewUsageLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLog) Unwrap() *UsageLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLog) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	if v := _m.RequestedModel; v != nil {
		builder.WriteString("requested_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamModel; v != nil {
		builder.WriteString("upstream_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ModelMappingChain; v != nil {
		builder.WriteString("model_mapping_chain=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BillingTier; v != nil {
		builder.WriteString("billing_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BillingMode; v != nil {
		builder.WriteString("billing_mode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PromptCacheKeyHash; v != nil {
		builder.WriteString("prompt_cache_key_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PromptCacheKeySource; v != nil {
		builder.WriteString("prompt_cache_key_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PromptCachePrefixHash; v != nil {
		builder.WriteString("prompt_cache_prefix_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PromptCacheToolsHash; v != nil {
		builder.WriteString("prompt_cache_tools_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PromptCacheSystemHash; v != nil {
		builder.WriteString("prompt_cache_system_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_5m_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation5mTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_1h_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreation1hTokens))
	builder.WriteString(", ")
	builder.WriteString("input_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputCost))
	builder.WriteString(", ")
	builder.WriteString("output_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputCost))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationCost))
	builder.WriteString(", ")
	builder.WriteString("cache_read_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadCost))
	builder.WriteString(", ")
	builder.WriteString("total_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("long_context_billing_applied=")
	builder.WriteString(fmt.Sprintf("%v", _m.LongContextBillingApplied))
	builder.WriteString(", ")
	if v := _m.AccountRateMultiplier; v != nil {
		builder.WriteString("account_rate_multiplier=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("billing_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingType))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", _m.Stream))
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FirstTokenMs; v != nil {
		builder.WriteString("first_token_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClientTransport; v != nil {
		builder.WriteString("client_transport=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AuthLatencyMs; v != nil {
		builder.WriteString("auth_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RoutingLatencyMs; v != nil {
		builder.WriteString("routing_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamLatencyMs; v != nil {
		builder.WriteString("upstream_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResponseLatencyMs; v != nil {
		builder.WriteString("response_latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestStartedAt; v != nil {
		builder.WriteString("request_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RequestTotalMs; v != nil {
		builder.WriteString("request_total_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestBodyReadMs; v != nil {
		builder.WriteString("request_body_read_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestBodyBytes; v != nil {
		builder.WriteString("request_body_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamConnectionReused; v != nil {
		builder.WriteString("upstream_connection_reused=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamConnectionReadyMs; v != nil {
		builder.WriteString("upstream_connection_ready_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamDNSLookupMs; v != nil {
		builder.WriteString("upstream_dns_lookup_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamTCPConnectMs; v != nil {
		builder.WriteString("upstream_tcp_connect_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamTLSHandshakeMs; v != nil {
		builder.WriteString("upstream_tls_handshake_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamRequestHeadersWrittenMs; v != nil {
		builder.WriteString("upstream_request_headers_written_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamRequestWrittenMs; v != nil {
		builder.WriteString("upstream_request_written_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamFirstByteMs; v != nil {
		builder.WriteString("upstream_first_byte_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamResponseHeadersReceivedMs; v != nil {
		builder.WriteString("upstream_response_headers_received_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamResponseBodyFirstByteMs; v != nil {
		builder.WriteString("upstream_response_body_first_byte_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamFirstEventMs; v != nil {
		builder.WriteString("upstream_first_event_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestFirstOutputCharacterMs; v != nil {
		builder.WriteString("request_first_output_character_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RequestFirstTokenMs; v != nil {
		builder.WriteString("request_first_token_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RouteKind; v != nil {
		builder.WriteString("route_kind=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProxyIDSnapshot; v != nil {
		builder.WriteString("proxy_id_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProxyNameSnapshot; v != nil {
		builder.WriteString("proxy_name_snapshot=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProxyProtocolSnapshot; v != nil {
		builder.WriteString("proxy_protocol_snapshot=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RouteFingerprint; v != nil {
		builder.WriteString("route_fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FinalUpstreamStatus; v != nil {
		builder.WriteString("final_upstream_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("account_switch_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountSwitchCount))
	builder.WriteString(", ")
	builder.WriteString("attempt_timeline=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptTimeline))
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IPAddress; v != nil {
		builder.WriteString("ip_address=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageCount))
	builder.WriteString(", ")
	if v := _m.ImageSize; v != nil {
		builder.WriteString("image_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageInputSize; v != nil {
		builder.WriteString("image_input_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageOutputSize; v != nil {
		builder.WriteString("image_output_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageSizeSource; v != nil {
		builder.WriteString("image_size_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_size_breakdown=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageSizeBreakdown))
	builder.WriteString(", ")
	builder.WriteString("video_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.VideoCount))
	builder.WriteString(", ")
	if v := _m.VideoResolution; v != nil {
		builder.WriteString("video_resolution=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.VideoDurationSeconds; v != nil {
		builder.WriteString("video_duration_seconds=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("cache_ttl_overridden=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheTTLOverridden))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogs is a parsable slice of UsageLog.
type UsageLogs []*UsageLog
