// Code generated by ent, DO NOT EDIT.

package externalorderfulfillment

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the externalorderfulfillment type in the database.
	Label = "external_order_fulfillment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPlatformOrderID holds the string denoting the platform_order_id field in the database.
	FieldPlatformOrderID = "platform_order_id"
	// FieldBuyerRef holds the string denoting the buyer_ref field in the database.
	FieldBuyerRef = "buyer_ref"
	// FieldSkuCode holds the string denoting the sku_code field in the database.
	FieldSkuCode = "sku_code"
	// FieldSkuName holds the string denoting the sku_name field in the database.
	FieldSkuName = "sku_name"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldRedeemCode holds the string denoting the redeem_code field in the database.
	FieldRedeemCode = "redeem_code"
	// FieldRedeemType holds the string denoting the redeem_type field in the database.
	FieldRedeemType = "redeem_type"
	// FieldRedeemValue holds the string denoting the redeem_value field in the database.
	FieldRedeemValue = "redeem_value"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldManualURL holds the string denoting the manual_url field in the database.
	FieldManualURL = "manual_url"
	// FieldDeliveryMessage holds the string denoting the delivery_message field in the database.
	FieldDeliveryMessage = "delivery_message"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNotifyStatus holds the string denoting the notify_status field in the database.
	FieldNotifyStatus = "notify_status"
	// FieldFailReason holds the string denoting the fail_reason field in the database.
	FieldFailReason = "fail_reason"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldDeliveredAt holds the string denoting the delivered_at field in the database.
	FieldDeliveredAt = "delivered_at"
	// FieldNotifiedAt holds the string denoting the notified_at field in the database.
	FieldNotifiedAt = "notified_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the externalorderfulfillment in the database.
	Table = "external_order_fulfillments"
)

// Columns holds all SQL columns for externalorderfulfillment fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldPlatformOrderID,
	FieldBuyerRef,
	FieldSkuCode,
	FieldSkuName,
	FieldAmount,
	FieldCurrency,
	FieldRedeemCodeID,
	FieldRedeemCode,
	FieldRedeemType,
	FieldRedeemValue,
	FieldGroupID,
	FieldValidityDays,
	FieldExpiresAt,
	FieldManualURL,
	FieldDeliveryMessage,
	FieldStatus,
	FieldNotifyStatus,
	FieldFailReason,
	FieldOperator,
	FieldDeliveredAt,
	FieldNotifiedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// PlatformOrderIDValidator is a validator for the "platform_order_id" field. It is called by the builders before save.
	PlatformOrderIDValidator func(string) error
	// BuyerRefValidator is a validator for the "buyer_ref" field. It is called by the builders before save.
	BuyerRefValidator func(string) error
	// SkuCodeValidator is a validator for the "sku_code" field. It is called by the builders before save.
	SkuCodeValidator func(string) error
	// SkuNameValidator is a validator for the "sku_name" field. It is called by the builders before save.
	SkuNameValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// RedeemCodeValidator is a validator for the "redeem_code" field. It is called by the builders before save.
	RedeemCodeValidator func(string) error
	// RedeemTypeValidator is a validator for the "redeem_type" field. It is called by the builders before save.
	RedeemTypeValidator func(string) error
	// DefaultRedeemValue holds the default value on creation for the "redeem_value" field.
	DefaultRedeemValue float64
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultNotifyStatus holds the default value on creation for the "notify_status" field.
	DefaultNotifyStatus string
	// NotifyStatusValidator is a validator for the "notify_status" field. It is called by the builders before save.
	NotifyStatusValidator func(string) error
	// OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	OperatorValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ExternalOrderFulfillment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPlatformOrderID orders the results by the platform_order_id field.
func ByPlatformOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformOrderID, opts...).ToFunc()
}

// ByBuyerRef orders the results by the buyer_ref field.
func ByBuyerRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerRef, opts...).ToFunc()
}

// BySkuCode orders the results by the sku_code field.
func BySkuCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkuCode, opts...).ToFunc()
}

// BySkuName orders the results by the sku_name field.
func BySkuName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkuName, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByRedeemCode orders the results by the redeem_code field.
func ByRedeemCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCode, opts...).ToFunc()
}

// ByRedeemType orders the results by the redeem_type field.
func ByRedeemType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemType, opts...).ToFunc()
}

// ByRedeemValue orders the results by the redeem_value field.
func ByRedeemValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemValue, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByManualURL orders the results by the manual_url field.
func ByManualURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualURL, opts...).ToFunc()
}

// ByDeliveryMessage orders the results by the delivery_message field.
func ByDeliveryMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryMessage, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNotifyStatus orders the results by the notify_status field.
func ByNotifyStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyStatus, opts...).ToFunc()
}

// ByFailReason orders the results by the fail_reason field.
func ByFailReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailReason, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByDeliveredAt orders the results by the delivered_at field.
func ByDeliveredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveredAt, opts...).ToFunc()
}

// ByNotifiedAt orders the results by the notified_at field.
func ByNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifiedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
