// Code generated by ent, DO NOT EDIT.

package externalorderfulfillment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldPlatform, v))
}

// PlatformOrderID applies equality check predicate on the "platform_order_id" field. It's identical to PlatformOrderIDEQ.
func PlatformOrderID(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldPlatformOrderID, v))
}

// BuyerRef applies equality check predicate on the "buyer_ref" field. It's identical to BuyerRefEQ.
func BuyerRef(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldBuyerRef, v))
}

// SkuCode applies equality check predicate on the "sku_code" field. It's identical to SkuCodeEQ.
func SkuCode(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldSkuCode, v))
}

// SkuName applies equality check predicate on the "sku_name" field. It's identical to SkuNameEQ.
func SkuName(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldSkuName, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldCurrency, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCode applies equality check predicate on the "redeem_code" field. It's identical to RedeemCodeEQ.
func RedeemCode(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemCode, v))
}

// RedeemType applies equality check predicate on the "redeem_type" field. It's identical to RedeemTypeEQ.
func RedeemType(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemType, v))
}

// RedeemValue applies equality check predicate on the "redeem_value" field. It's identical to RedeemValueEQ.
func RedeemValue(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemValue, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldGroupID, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldValidityDays, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldExpiresAt, v))
}

// ManualURL applies equality check predicate on the "manual_url" field. It's identical to ManualURLEQ.
func ManualURL(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldManualURL, v))
}

// DeliveryMessage applies equality check predicate on the "delivery_message" field. It's identical to DeliveryMessageEQ.
func DeliveryMessage(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldDeliveryMessage, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldStatus, v))
}

// NotifyStatus applies equality check predicate on the "notify_status" field. It's identical to NotifyStatusEQ.
func NotifyStatus(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldNotifyStatus, v))
}

// FailReason applies equality check predicate on the "fail_reason" field. It's identical to FailReasonEQ.
func FailReason(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldFailReason, v))
}

// Operator applies equality check predicate on the "operator" field. It's identical to OperatorEQ.
func Operator(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldOperator, v))
}

// DeliveredAt applies equality check predicate on the "delivered_at" field. It's identical to DeliveredAtEQ.
func DeliveredAt(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldDeliveredAt, v))
}

// NotifiedAt applies equality check predicate on the "notified_at" field. It's identical to NotifiedAtEQ.
func NotifiedAt(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldNotifiedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldPlatform, v))
}

// PlatformOrderIDEQ applies the EQ predicate on the "platform_order_id" field.
func PlatformOrderIDEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldPlatformOrderID, v))
}

// PlatformOrderIDNEQ applies the NEQ predicate on the "platform_order_id" field.
func PlatformOrderIDNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldPlatformOrderID, v))
}

// PlatformOrderIDIn applies the In predicate on the "platform_order_id" field.
func PlatformOrderIDIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldPlatformOrderID, vs...))
}

// PlatformOrderIDNotIn applies the NotIn predicate on the "platform_order_id" field.
func PlatformOrderIDNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldPlatformOrderID, vs...))
}

// PlatformOrderIDGT applies the GT predicate on the "platform_order_id" field.
func PlatformOrderIDGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldPlatformOrderID, v))
}

// PlatformOrderIDGTE applies the GTE predicate on the "platform_order_id" field.
func PlatformOrderIDGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldPlatformOrderID, v))
}

// PlatformOrderIDLT applies the LT predicate on the "platform_order_id" field.
func PlatformOrderIDLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldPlatformOrderID, v))
}

// PlatformOrderIDLTE applies the LTE predicate on the "platform_order_id" field.
func PlatformOrderIDLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldPlatformOrderID, v))
}

// PlatformOrderIDContains applies the Contains predicate on the "platform_order_id" field.
func PlatformOrderIDContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldPlatformOrderID, v))
}

// PlatformOrderIDHasPrefix applies the HasPrefix predicate on the "platform_order_id" field.
func PlatformOrderIDHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldPlatformOrderID, v))
}

// PlatformOrderIDHasSuffix applies the HasSuffix predicate on the "platform_order_id" field.
func PlatformOrderIDHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldPlatformOrderID, v))
}

// PlatformOrderIDEqualFold applies the EqualFold predicate on the "platform_order_id" field.
func PlatformOrderIDEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldPlatformOrderID, v))
}

// PlatformOrderIDContainsFold applies the ContainsFold predicate on the "platform_order_id" field.
func PlatformOrderIDContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldPlatformOrderID, v))
}

// BuyerRefEQ applies the EQ predicate on the "buyer_ref" field.
func BuyerRefEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldBuyerRef, v))
}

// BuyerRefNEQ applies the NEQ predicate on the "buyer_ref" field.
func BuyerRefNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldBuyerRef, v))
}

// BuyerRefIn applies the In predicate on the "buyer_ref" field.
func BuyerRefIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldBuyerRef, vs...))
}

// BuyerRefNotIn applies the NotIn predicate on the "buyer_ref" field.
func BuyerRefNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldBuyerRef, vs...))
}

// BuyerRefGT applies the GT predicate on the "buyer_ref" field.
func BuyerRefGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldBuyerRef, v))
}

// BuyerRefGTE applies the GTE predicate on the "buyer_ref" field.
func BuyerRefGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldBuyerRef, v))
}

// BuyerRefLT applies the LT predicate on the "buyer_ref" field.
func BuyerRefLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldBuyerRef, v))
}

// BuyerRefLTE applies the LTE predicate on the "buyer_ref" field.
func BuyerRefLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldBuyerRef, v))
}

// BuyerRefContains applies the Contains predicate on the "buyer_ref" field.
func BuyerRefContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldBuyerRef, v))
}

// BuyerRefHasPrefix applies the HasPrefix predicate on the "buyer_ref" field.
func BuyerRefHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldBuyerRef, v))
}

// BuyerRefHasSuffix applies the HasSuffix predicate on the "buyer_ref" field.
func BuyerRefHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldBuyerRef, v))
}

// BuyerRefIsNil applies the IsNil predicate on the "buyer_ref" field.
func BuyerRefIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldBuyerRef))
}

// BuyerRefNotNil applies the NotNil predicate on the "buyer_ref" field.
func BuyerRefNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldBuyerRef))
}

// BuyerRefEqualFold applies the EqualFold predicate on the "buyer_ref" field.
func BuyerRefEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldBuyerRef, v))
}

// BuyerRefContainsFold applies the ContainsFold predicate on the "buyer_ref" field.
func BuyerRefContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldBuyerRef, v))
}

// SkuCodeEQ applies the EQ predicate on the "sku_code" field.
func SkuCodeEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldSkuCode, v))
}

// SkuCodeNEQ applies the NEQ predicate on the "sku_code" field.
func SkuCodeNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldSkuCode, v))
}

// SkuCodeIn applies the In predicate on the "sku_code" field.
func SkuCodeIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldSkuCode, vs...))
}

// SkuCodeNotIn applies the NotIn predicate on the "sku_code" field.
func SkuCodeNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldSkuCode, vs...))
}

// SkuCodeGT applies the GT predicate on the "sku_code" field.
func SkuCodeGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldSkuCode, v))
}

// SkuCodeGTE applies the GTE predicate on the "sku_code" field.
func SkuCodeGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldSkuCode, v))
}

// SkuCodeLT applies the LT predicate on the "sku_code" field.
func SkuCodeLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldSkuCode, v))
}

// SkuCodeLTE applies the LTE predicate on the "sku_code" field.
func SkuCodeLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldSkuCode, v))
}

// SkuCodeContains applies the Contains predicate on the "sku_code" field.
func SkuCodeContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldSkuCode, v))
}

// SkuCodeHasPrefix applies the HasPrefix predicate on the "sku_code" field.
func SkuCodeHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldSkuCode, v))
}

// SkuCodeHasSuffix applies the HasSuffix predicate on the "sku_code" field.
func SkuCodeHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldSkuCode, v))
}

// SkuCodeEqualFold applies the EqualFold predicate on the "sku_code" field.
func SkuCodeEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldSkuCode, v))
}

// SkuCodeContainsFold applies the ContainsFold predicate on the "sku_code" field.
func SkuCodeContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldSkuCode, v))
}

// SkuNameEQ applies the EQ predicate on the "sku_name" field.
func SkuNameEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldSkuName, v))
}

// SkuNameNEQ applies the NEQ predicate on the "sku_name" field.
func SkuNameNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldSkuName, v))
}

// SkuNameIn applies the In predicate on the "sku_name" field.
func SkuNameIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldSkuName, vs...))
}

// SkuNameNotIn applies the NotIn predicate on the "sku_name" field.
func SkuNameNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldSkuName, vs...))
}

// SkuNameGT applies the GT predicate on the "sku_name" field.
func SkuNameGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldSkuName, v))
}

// SkuNameGTE applies the GTE predicate on the "sku_name" field.
func SkuNameGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldSkuName, v))
}

// SkuNameLT applies the LT predicate on the "sku_name" field.
func SkuNameLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldSkuName, v))
}

// SkuNameLTE applies the LTE predicate on the "sku_name" field.
func SkuNameLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldSkuName, v))
}

// SkuNameContains applies the Contains predicate on the "sku_name" field.
func SkuNameContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldSkuName, v))
}

// SkuNameHasPrefix applies the HasPrefix predicate on the "sku_name" field.
func SkuNameHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldSkuName, v))
}

// SkuNameHasSuffix applies the HasSuffix predicate on the "sku_name" field.
func SkuNameHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldSkuName, v))
}

// SkuNameIsNil applies the IsNil predicate on the "sku_name" field.
func SkuNameIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldSkuName))
}

// SkuNameNotNil applies the NotNil predicate on the "sku_name" field.
func SkuNameNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldSkuName))
}

// SkuNameEqualFold applies the EqualFold predicate on the "sku_name" field.
func SkuNameEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldSkuName, v))
}

// SkuNameContainsFold applies the ContainsFold predicate on the "sku_name" field.
func SkuNameContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldSkuName, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldCurrency, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDIsNil applies the IsNil predicate on the "redeem_code_id" field.
func RedeemCodeIDIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldRedeemCodeID))
}

// RedeemCodeIDNotNil applies the NotNil predicate on the "redeem_code_id" field.
func RedeemCodeIDNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldRedeemCodeID))
}

// RedeemCodeEQ applies the EQ predicate on the "redeem_code" field.
func RedeemCodeEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemCode, v))
}

// RedeemCodeNEQ applies the NEQ predicate on the "redeem_code" field.
func RedeemCodeNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldRedeemCode, v))
}

// RedeemCodeIn applies the In predicate on the "redeem_code" field.
func RedeemCodeIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldRedeemCode, vs...))
}

// RedeemCodeNotIn applies the NotIn predicate on the "redeem_code" field.
func RedeemCodeNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldRedeemCode, vs...))
}

// RedeemCodeGT applies the GT predicate on the "redeem_code" field.
func RedeemCodeGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldRedeemCode, v))
}

// RedeemCodeGTE applies the GTE predicate on the "redeem_code" field.
func RedeemCodeGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldRedeemCode, v))
}

// RedeemCodeLT applies the LT predicate on the "redeem_code" field.
func RedeemCodeLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldRedeemCode, v))
}

// RedeemCodeLTE applies the LTE predicate on the "redeem_code" field.
func RedeemCodeLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldRedeemCode, v))
}

// RedeemCodeContains applies the Contains predicate on the "redeem_code" field.
func RedeemCodeContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldRedeemCode, v))
}

// RedeemCodeHasPrefix applies the HasPrefix predicate on the "redeem_code" field.
func RedeemCodeHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldRedeemCode, v))
}

// RedeemCodeHasSuffix applies the HasSuffix predicate on the "redeem_code" field.
func RedeemCodeHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldRedeemCode, v))
}

// RedeemCodeIsNil applies the IsNil predicate on the "redeem_code" field.
func RedeemCodeIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldRedeemCode))
}

// RedeemCodeNotNil applies the NotNil predicate on the "redeem_code" field.
func RedeemCodeNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldRedeemCode))
}

// RedeemCodeEqualFold applies the EqualFold predicate on the "redeem_code" field.
func RedeemCodeEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldRedeemCode, v))
}

// RedeemCodeContainsFold applies the ContainsFold predicate on the "redeem_code" field.
func RedeemCodeContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldRedeemCode, v))
}

// RedeemTypeEQ applies the EQ predicate on the "redeem_type" field.
func RedeemTypeEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemType, v))
}

// RedeemTypeNEQ applies the NEQ predicate on the "redeem_type" field.
func RedeemTypeNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldRedeemType, v))
}

// RedeemTypeIn applies the In predicate on the "redeem_type" field.
func RedeemTypeIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldRedeemType, vs...))
}

// RedeemTypeNotIn applies the NotIn predicate on the "redeem_type" field.
func RedeemTypeNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldRedeemType, vs...))
}

// RedeemTypeGT applies the GT predicate on the "redeem_type" field.
func RedeemTypeGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldRedeemType, v))
}

// RedeemTypeGTE applies the GTE predicate on the "redeem_type" field.
func RedeemTypeGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldRedeemType, v))
}

// RedeemTypeLT applies the LT predicate on the "redeem_type" field.
func RedeemTypeLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldRedeemType, v))
}

// RedeemTypeLTE applies the LTE predicate on the "redeem_type" field.
func RedeemTypeLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldRedeemType, v))
}

// RedeemTypeContains applies the Contains predicate on the "redeem_type" field.
func RedeemTypeContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldRedeemType, v))
}

// RedeemTypeHasPrefix applies the HasPrefix predicate on the "redeem_type" field.
func RedeemTypeHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldRedeemType, v))
}

// RedeemTypeHasSuffix applies the HasSuffix predicate on the "redeem_type" field.
func RedeemTypeHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldRedeemType, v))
}

// RedeemTypeEqualFold applies the EqualFold predicate on the "redeem_type" field.
func RedeemTypeEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldRedeemType, v))
}

// RedeemTypeContainsFold applies the ContainsFold predicate on the "redeem_type" field.
func RedeemTypeContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldRedeemType, v))
}

// RedeemValueEQ applies the EQ predicate on the "redeem_value" field.
func RedeemValueEQ(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldRedeemValue, v))
}

// RedeemValueNEQ applies the NEQ predicate on the "redeem_value" field.
func RedeemValueNEQ(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldRedeemValue, v))
}

// RedeemValueIn applies the In predicate on the "redeem_value" field.
func RedeemValueIn(vs ...float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldRedeemValue, vs...))
}

// RedeemValueNotIn applies the NotIn predicate on the "redeem_value" field.
func RedeemValueNotIn(vs ...float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldRedeemValue, vs...))
}

// RedeemValueGT applies the GT predicate on the "redeem_value" field.
func RedeemValueGT(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldRedeemValue, v))
}

// RedeemValueGTE applies the GTE predicate on the "redeem_value" field.
func RedeemValueGTE(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldRedeemValue, v))
}

// RedeemValueLT applies the LT predicate on the "redeem_value" field.
func RedeemValueLT(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldRedeemValue, v))
}

// RedeemValueLTE applies the LTE predicate on the "redeem_value" field.
func RedeemValueLTE(v float64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldRedeemValue, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldGroupID))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldValidityDays, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldExpiresAt))
}

// ManualURLEQ applies the EQ predicate on the "manual_url" field.
func ManualURLEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldManualURL, v))
}

// ManualURLNEQ applies the NEQ predicate on the "manual_url" field.
func ManualURLNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldManualURL, v))
}

// ManualURLIn applies the In predicate on the "manual_url" field.
func ManualURLIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldManualURL, vs...))
}

// ManualURLNotIn applies the NotIn predicate on the "manual_url" field.
func ManualURLNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldManualURL, vs...))
}

// ManualURLGT applies the GT predicate on the "manual_url" field.
func ManualURLGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldManualURL, v))
}

// ManualURLGTE applies the GTE predicate on the "manual_url" field.
func ManualURLGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldManualURL, v))
}

// ManualURLLT applies the LT predicate on the "manual_url" field.
func ManualURLLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldManualURL, v))
}

// ManualURLLTE applies the LTE predicate on the "manual_url" field.
func ManualURLLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldManualURL, v))
}

// ManualURLContains applies the Contains predicate on the "manual_url" field.
func ManualURLContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldManualURL, v))
}

// ManualURLHasPrefix applies the HasPrefix predicate on the "manual_url" field.
func ManualURLHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldManualURL, v))
}

// ManualURLHasSuffix applies the HasSuffix predicate on the "manual_url" field.
func ManualURLHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldManualURL, v))
}

// ManualURLIsNil applies the IsNil predicate on the "manual_url" field.
func ManualURLIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldManualURL))
}

// ManualURLNotNil applies the NotNil predicate on the "manual_url" field.
func ManualURLNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldManualURL))
}

// ManualURLEqualFold applies the EqualFold predicate on the "manual_url" field.
func ManualURLEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldManualURL, v))
}

// ManualURLContainsFold applies the ContainsFold predicate on the "manual_url" field.
func ManualURLContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldManualURL, v))
}

// DeliveryMessageEQ applies the EQ predicate on the "delivery_message" field.
func DeliveryMessageEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldDeliveryMessage, v))
}

// DeliveryMessageNEQ applies the NEQ predicate on the "delivery_message" field.
func DeliveryMessageNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldDeliveryMessage, v))
}

// DeliveryMessageIn applies the In predicate on the "delivery_message" field.
func DeliveryMessageIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldDeliveryMessage, vs...))
}

// DeliveryMessageNotIn applies the NotIn predicate on the "delivery_message" field.
func DeliveryMessageNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldDeliveryMessage, vs...))
}

// DeliveryMessageGT applies the GT predicate on the "delivery_message" field.
func DeliveryMessageGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldDeliveryMessage, v))
}

// DeliveryMessageGTE applies the GTE predicate on the "delivery_message" field.
func DeliveryMessageGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldDeliveryMessage, v))
}

// DeliveryMessageLT applies the LT predicate on the "delivery_message" field.
func DeliveryMessageLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldDeliveryMessage, v))
}

// DeliveryMessageLTE applies the LTE predicate on the "delivery_message" field.
func DeliveryMessageLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldDeliveryMessage, v))
}

// DeliveryMessageContains applies the Contains predicate on the "delivery_message" field.
func DeliveryMessageContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldDeliveryMessage, v))
}

// DeliveryMessageHasPrefix applies the HasPrefix predicate on the "delivery_message" field.
func DeliveryMessageHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldDeliveryMessage, v))
}

// DeliveryMessageHasSuffix applies the HasSuffix predicate on the "delivery_message" field.
func DeliveryMessageHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldDeliveryMessage, v))
}

// DeliveryMessageIsNil applies the IsNil predicate on the "delivery_message" field.
func DeliveryMessageIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldDeliveryMessage))
}

// DeliveryMessageNotNil applies the NotNil predicate on the "delivery_message" field.
func DeliveryMessageNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldDeliveryMessage))
}

// DeliveryMessageEqualFold applies the EqualFold predicate on the "delivery_message" field.
func DeliveryMessageEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldDeliveryMessage, v))
}

// DeliveryMessageContainsFold applies the ContainsFold predicate on the "delivery_message" field.
func DeliveryMessageContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldDeliveryMessage, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldStatus, v))
}

// NotifyStatusEQ applies the EQ predicate on the "notify_status" field.
func NotifyStatusEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldNotifyStatus, v))
}

// NotifyStatusNEQ applies the NEQ predicate on the "notify_status" field.
func NotifyStatusNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldNotifyStatus, v))
}

// NotifyStatusIn applies the In predicate on the "notify_status" field.
func NotifyStatusIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldNotifyStatus, vs...))
}

// NotifyStatusNotIn applies the NotIn predicate on the "notify_status" field.
func NotifyStatusNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldNotifyStatus, vs...))
}

// NotifyStatusGT applies the GT predicate on the "notify_status" field.
func NotifyStatusGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldNotifyStatus, v))
}

// NotifyStatusGTE applies the GTE predicate on the "notify_status" field.
func NotifyStatusGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldNotifyStatus, v))
}

// NotifyStatusLT applies the LT predicate on the "notify_status" field.
func NotifyStatusLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldNotifyStatus, v))
}

// NotifyStatusLTE applies the LTE predicate on the "notify_status" field.
func NotifyStatusLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldNotifyStatus, v))
}

// NotifyStatusContains applies the Contains predicate on the "notify_status" field.
func NotifyStatusContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldNotifyStatus, v))
}

// NotifyStatusHasPrefix applies the HasPrefix predicate on the "notify_status" field.
func NotifyStatusHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldNotifyStatus, v))
}

// NotifyStatusHasSuffix applies the HasSuffix predicate on the "notify_status" field.
func NotifyStatusHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldNotifyStatus, v))
}

// NotifyStatusEqualFold applies the EqualFold predicate on the "notify_status" field.
func NotifyStatusEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldNotifyStatus, v))
}

// NotifyStatusContainsFold applies the ContainsFold predicate on the "notify_status" field.
func NotifyStatusContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldNotifyStatus, v))
}

// FailReasonEQ applies the EQ predicate on the "fail_reason" field.
func FailReasonEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldFailReason, v))
}

// FailReasonNEQ applies the NEQ predicate on the "fail_reason" field.
func FailReasonNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldFailReason, v))
}

// FailReasonIn applies the In predicate on the "fail_reason" field.
func FailReasonIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldFailReason, vs...))
}

// FailReasonNotIn applies the NotIn predicate on the "fail_reason" field.
func FailReasonNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldFailReason, vs...))
}

// FailReasonGT applies the GT predicate on the "fail_reason" field.
func FailReasonGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldFailReason, v))
}

// FailReasonGTE applies the GTE predicate on the "fail_reason" field.
func FailReasonGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldFailReason, v))
}

// FailReasonLT applies the LT predicate on the "fail_reason" field.
func FailReasonLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldFailReason, v))
}

// FailReasonLTE applies the LTE predicate on the "fail_reason" field.
func FailReasonLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldFailReason, v))
}

// FailReasonContains applies the Contains predicate on the "fail_reason" field.
func FailReasonContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldFailReason, v))
}

// FailReasonHasPrefix applies the HasPrefix predicate on the "fail_reason" field.
func FailReasonHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldFailReason, v))
}

// FailReasonHasSuffix applies the HasSuffix predicate on the "fail_reason" field.
func FailReasonHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldFailReason, v))
}

// FailReasonIsNil applies the IsNil predicate on the "fail_reason" field.
func FailReasonIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldFailReason))
}

// FailReasonNotNil applies the NotNil predicate on the "fail_reason" field.
func FailReasonNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldFailReason))
}

// FailReasonEqualFold applies the EqualFold predicate on the "fail_reason" field.
func FailReasonEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldFailReason, v))
}

// FailReasonContainsFold applies the ContainsFold predicate on the "fail_reason" field.
func FailReasonContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldFailReason, v))
}

// OperatorEQ applies the EQ predicate on the "operator" field.
func OperatorEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldOperator, v))
}

// OperatorNEQ applies the NEQ predicate on the "operator" field.
func OperatorNEQ(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldOperator, v))
}

// OperatorIn applies the In predicate on the "operator" field.
func OperatorIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldOperator, vs...))
}

// OperatorNotIn applies the NotIn predicate on the "operator" field.
func OperatorNotIn(vs ...string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldOperator, vs...))
}

// OperatorGT applies the GT predicate on the "operator" field.
func OperatorGT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldOperator, v))
}

// OperatorGTE applies the GTE predicate on the "operator" field.
func OperatorGTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldOperator, v))
}

// OperatorLT applies the LT predicate on the "operator" field.
func OperatorLT(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldOperator, v))
}

// OperatorLTE applies the LTE predicate on the "operator" field.
func OperatorLTE(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldOperator, v))
}

// OperatorContains applies the Contains predicate on the "operator" field.
func OperatorContains(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContains(FieldOperator, v))
}

// OperatorHasPrefix applies the HasPrefix predicate on the "operator" field.
func OperatorHasPrefix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasPrefix(FieldOperator, v))
}

// OperatorHasSuffix applies the HasSuffix predicate on the "operator" field.
func OperatorHasSuffix(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldHasSuffix(FieldOperator, v))
}

// OperatorIsNil applies the IsNil predicate on the "operator" field.
func OperatorIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldOperator))
}

// OperatorNotNil applies the NotNil predicate on the "operator" field.
func OperatorNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldOperator))
}

// OperatorEqualFold applies the EqualFold predicate on the "operator" field.
func OperatorEqualFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEqualFold(FieldOperator, v))
}

// OperatorContainsFold applies the ContainsFold predicate on the "operator" field.
func OperatorContainsFold(v string) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldContainsFold(FieldOperator, v))
}

// DeliveredAtEQ applies the EQ predicate on the "delivered_at" field.
func DeliveredAtEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldDeliveredAt, v))
}

// DeliveredAtNEQ applies the NEQ predicate on the "delivered_at" field.
func DeliveredAtNEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldDeliveredAt, v))
}

// DeliveredAtIn applies the In predicate on the "delivered_at" field.
func DeliveredAtIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldDeliveredAt, vs...))
}

// DeliveredAtNotIn applies the NotIn predicate on the "delivered_at" field.
func DeliveredAtNotIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldDeliveredAt, vs...))
}

// DeliveredAtGT applies the GT predicate on the "delivered_at" field.
func DeliveredAtGT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldDeliveredAt, v))
}

// DeliveredAtGTE applies the GTE predicate on the "delivered_at" field.
func DeliveredAtGTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldDeliveredAt, v))
}

// DeliveredAtLT applies the LT predicate on the "delivered_at" field.
func DeliveredAtLT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldDeliveredAt, v))
}

// DeliveredAtLTE applies the LTE predicate on the "delivered_at" field.
func DeliveredAtLTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldDeliveredAt, v))
}

// DeliveredAtIsNil applies the IsNil predicate on the "delivered_at" field.
func DeliveredAtIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldDeliveredAt))
}

// DeliveredAtNotNil applies the NotNil predicate on the "delivered_at" field.
func DeliveredAtNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldDeliveredAt))
}

// NotifiedAtEQ applies the EQ predicate on the "notified_at" field.
func NotifiedAtEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldNotifiedAt, v))
}

// NotifiedAtNEQ applies the NEQ predicate on the "notified_at" field.
func NotifiedAtNEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldNotifiedAt, v))
}

// NotifiedAtIn applies the In predicate on the "notified_at" field.
func NotifiedAtIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldNotifiedAt, vs...))
}

// NotifiedAtNotIn applies the NotIn predicate on the "notified_at" field.
func NotifiedAtNotIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldNotifiedAt, vs...))
}

// NotifiedAtGT applies the GT predicate on the "notified_at" field.
func NotifiedAtGT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldNotifiedAt, v))
}

// NotifiedAtGTE applies the GTE predicate on the "notified_at" field.
func NotifiedAtGTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldNotifiedAt, v))
}

// NotifiedAtLT applies the LT predicate on the "notified_at" field.
func NotifiedAtLT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldNotifiedAt, v))
}

// NotifiedAtLTE applies the LTE predicate on the "notified_at" field.
func NotifiedAtLTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldNotifiedAt, v))
}

// NotifiedAtIsNil applies the IsNil predicate on the "notified_at" field.
func NotifiedAtIsNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIsNull(FieldNotifiedAt))
}

// NotifiedAtNotNil applies the NotNil predicate on the "notified_at" field.
func NotifiedAtNotNil() predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotNull(FieldNotifiedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalOrderFulfillment) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalOrderFulfillment) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalOrderFulfillment) predicate.ExternalOrderFulfillment {
	return predicate.ExternalOrderFulfillment(sql.NotPredicates(p))
}
