// Code generated by ent, DO NOT EDIT.

package externalfulfillmentsku

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the externalfulfillmentsku type in the database.
	Label = "external_fulfillment_sku"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldSkuCode holds the string denoting the sku_code field in the database.
	FieldSkuCode = "sku_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldRedeemType holds the string denoting the redeem_type field in the database.
	FieldRedeemType = "redeem_type"
	// FieldRedeemValue holds the string denoting the redeem_value field in the database.
	FieldRedeemValue = "redeem_value"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldExpiresInDays holds the string denoting the expires_in_days field in the database.
	FieldExpiresInDays = "expires_in_days"
	// FieldManualURL holds the string denoting the manual_url field in the database.
	FieldManualURL = "manual_url"
	// FieldDeliveryTemplate holds the string denoting the delivery_template field in the database.
	FieldDeliveryTemplate = "delivery_template"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the externalfulfillmentsku in the database.
	Table = "external_fulfillment_skus"
)

// Columns holds all SQL columns for externalfulfillmentsku fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldSkuCode,
	FieldName,
	FieldAmount,
	FieldCurrency,
	FieldRedeemType,
	FieldRedeemValue,
	FieldGroupID,
	FieldValidityDays,
	FieldExpiresInDays,
	FieldManualURL,
	FieldDeliveryTemplate,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// SkuCodeValidator is a validator for the "sku_code" field. It is called by the builders before save.
	SkuCodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// RedeemTypeValidator is a validator for the "redeem_type" field. It is called by the builders before save.
	RedeemTypeValidator func(string) error
	// DefaultRedeemValue holds the default value on creation for the "redeem_value" field.
	DefaultRedeemValue float64
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ExternalFulfillmentSKU queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// BySkuCode orders the results by the sku_code field.
func BySkuCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkuCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByRedeemType orders the results by the redeem_type field.
func ByRedeemType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemType, opts...).ToFunc()
}

// ByRedeemValue orders the results by the redeem_value field.
func ByRedeemValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemValue, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByExpiresInDays orders the results by the expires_in_days field.
func ByExpiresInDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresInDays, opts...).ToFunc()
}

// ByManualURL orders the results by the manual_url field.
func ByManualURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManualURL, opts...).ToFunc()
}

// ByDeliveryTemplate orders the results by the delivery_template field.
func ByDeliveryTemplate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryTemplate, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
