// Code generated by ent, DO NOT EDIT.

package externalfulfillmentsku

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldPlatform, v))
}

// SkuCode applies equality check predicate on the "sku_code" field. It's identical to SkuCodeEQ.
func SkuCode(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldSkuCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldName, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldCurrency, v))
}

// RedeemType applies equality check predicate on the "redeem_type" field. It's identical to RedeemTypeEQ.
func RedeemType(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldRedeemType, v))
}

// RedeemValue applies equality check predicate on the "redeem_value" field. It's identical to RedeemValueEQ.
func RedeemValue(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldRedeemValue, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldGroupID, v))
}

// ValidityDays applies equality check predicate on the "validity_days" field. It's identical to ValidityDaysEQ.
func ValidityDays(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldValidityDays, v))
}

// ExpiresInDays applies equality check predicate on the "expires_in_days" field. It's identical to ExpiresInDaysEQ.
func ExpiresInDays(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldExpiresInDays, v))
}

// ManualURL applies equality check predicate on the "manual_url" field. It's identical to ManualURLEQ.
func ManualURL(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldManualURL, v))
}

// DeliveryTemplate applies equality check predicate on the "delivery_template" field. It's identical to DeliveryTemplateEQ.
func DeliveryTemplate(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldDeliveryTemplate, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldPlatform, v))
}

// SkuCodeEQ applies the EQ predicate on the "sku_code" field.
func SkuCodeEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldSkuCode, v))
}

// SkuCodeNEQ applies the NEQ predicate on the "sku_code" field.
func SkuCodeNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldSkuCode, v))
}

// SkuCodeIn applies the In predicate on the "sku_code" field.
func SkuCodeIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldSkuCode, vs...))
}

// SkuCodeNotIn applies the NotIn predicate on the "sku_code" field.
func SkuCodeNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldSkuCode, vs...))
}

// SkuCodeGT applies the GT predicate on the "sku_code" field.
func SkuCodeGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldSkuCode, v))
}

// SkuCodeGTE applies the GTE predicate on the "sku_code" field.
func SkuCodeGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldSkuCode, v))
}

// SkuCodeLT applies the LT predicate on the "sku_code" field.
func SkuCodeLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldSkuCode, v))
}

// SkuCodeLTE applies the LTE predicate on the "sku_code" field.
func SkuCodeLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldSkuCode, v))
}

// SkuCodeContains applies the Contains predicate on the "sku_code" field.
func SkuCodeContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldSkuCode, v))
}

// SkuCodeHasPrefix applies the HasPrefix predicate on the "sku_code" field.
func SkuCodeHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldSkuCode, v))
}

// SkuCodeHasSuffix applies the HasSuffix predicate on the "sku_code" field.
func SkuCodeHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldSkuCode, v))
}

// SkuCodeEqualFold applies the EqualFold predicate on the "sku_code" field.
func SkuCodeEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldSkuCode, v))
}

// SkuCodeContainsFold applies the ContainsFold predicate on the "sku_code" field.
func SkuCodeContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldSkuCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldName, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldCurrency, v))
}

// RedeemTypeEQ applies the EQ predicate on the "redeem_type" field.
func RedeemTypeEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldRedeemType, v))
}

// RedeemTypeNEQ applies the NEQ predicate on the "redeem_type" field.
func RedeemTypeNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldRedeemType, v))
}

// RedeemTypeIn applies the In predicate on the "redeem_type" field.
func RedeemTypeIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldRedeemType, vs...))
}

// RedeemTypeNotIn applies the NotIn predicate on the "redeem_type" field.
func RedeemTypeNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldRedeemType, vs...))
}

// RedeemTypeGT applies the GT predicate on the "redeem_type" field.
func RedeemTypeGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldRedeemType, v))
}

// RedeemTypeGTE applies the GTE predicate on the "redeem_type" field.
func RedeemTypeGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldRedeemType, v))
}

// RedeemTypeLT applies the LT predicate on the "redeem_type" field.
func RedeemTypeLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldRedeemType, v))
}

// RedeemTypeLTE applies the LTE predicate on the "redeem_type" field.
func RedeemTypeLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldRedeemType, v))
}

// RedeemTypeContains applies the Contains predicate on the "redeem_type" field.
func RedeemTypeContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldRedeemType, v))
}

// RedeemTypeHasPrefix applies the HasPrefix predicate on the "redeem_type" field.
func RedeemTypeHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldRedeemType, v))
}

// RedeemTypeHasSuffix applies the HasSuffix predicate on the "redeem_type" field.
func RedeemTypeHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldRedeemType, v))
}

// RedeemTypeEqualFold applies the EqualFold predicate on the "redeem_type" field.
func RedeemTypeEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldRedeemType, v))
}

// RedeemTypeContainsFold applies the ContainsFold predicate on the "redeem_type" field.
func RedeemTypeContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldRedeemType, v))
}

// RedeemValueEQ applies the EQ predicate on the "redeem_value" field.
func RedeemValueEQ(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldRedeemValue, v))
}

// RedeemValueNEQ applies the NEQ predicate on the "redeem_value" field.
func RedeemValueNEQ(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldRedeemValue, v))
}

// RedeemValueIn applies the In predicate on the "redeem_value" field.
func RedeemValueIn(vs ...float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldRedeemValue, vs...))
}

// RedeemValueNotIn applies the NotIn predicate on the "redeem_value" field.
func RedeemValueNotIn(vs ...float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldRedeemValue, vs...))
}

// RedeemValueGT applies the GT predicate on the "redeem_value" field.
func RedeemValueGT(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldRedeemValue, v))
}

// RedeemValueGTE applies the GTE predicate on the "redeem_value" field.
func RedeemValueGTE(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldRedeemValue, v))
}

// RedeemValueLT applies the LT predicate on the "redeem_value" field.
func RedeemValueLT(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldRedeemValue, v))
}

// RedeemValueLTE applies the LTE predicate on the "redeem_value" field.
func RedeemValueLTE(v float64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldRedeemValue, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotNull(FieldGroupID))
}

// ValidityDaysEQ applies the EQ predicate on the "validity_days" field.
func ValidityDaysEQ(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldValidityDays, v))
}

// ValidityDaysNEQ applies the NEQ predicate on the "validity_days" field.
func ValidityDaysNEQ(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldValidityDays, v))
}

// ValidityDaysIn applies the In predicate on the "validity_days" field.
func ValidityDaysIn(vs ...int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldValidityDays, vs...))
}

// ValidityDaysNotIn applies the NotIn predicate on the "validity_days" field.
func ValidityDaysNotIn(vs ...int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldValidityDays, vs...))
}

// ValidityDaysGT applies the GT predicate on the "validity_days" field.
func ValidityDaysGT(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldValidityDays, v))
}

// ValidityDaysGTE applies the GTE predicate on the "validity_days" field.
func ValidityDaysGTE(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldValidityDays, v))
}

// ValidityDaysLT applies the LT predicate on the "validity_days" field.
func ValidityDaysLT(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldValidityDays, v))
}

// ValidityDaysLTE applies the LTE predicate on the "validity_days" field.
func ValidityDaysLTE(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldValidityDays, v))
}

// ExpiresInDaysEQ applies the EQ predicate on the "expires_in_days" field.
func ExpiresInDaysEQ(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldExpiresInDays, v))
}

// ExpiresInDaysNEQ applies the NEQ predicate on the "expires_in_days" field.
func ExpiresInDaysNEQ(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldExpiresInDays, v))
}

// ExpiresInDaysIn applies the In predicate on the "expires_in_days" field.
func ExpiresInDaysIn(vs ...int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldExpiresInDays, vs...))
}

// ExpiresInDaysNotIn applies the NotIn predicate on the "expires_in_days" field.
func ExpiresInDaysNotIn(vs ...int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldExpiresInDays, vs...))
}

// ExpiresInDaysGT applies the GT predicate on the "expires_in_days" field.
func ExpiresInDaysGT(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldExpiresInDays, v))
}

// ExpiresInDaysGTE applies the GTE predicate on the "expires_in_days" field.
func ExpiresInDaysGTE(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldExpiresInDays, v))
}

// ExpiresInDaysLT applies the LT predicate on the "expires_in_days" field.
func ExpiresInDaysLT(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldExpiresInDays, v))
}

// ExpiresInDaysLTE applies the LTE predicate on the "expires_in_days" field.
func ExpiresInDaysLTE(v int) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldExpiresInDays, v))
}

// ExpiresInDaysIsNil applies the IsNil predicate on the "expires_in_days" field.
func ExpiresInDaysIsNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIsNull(FieldExpiresInDays))
}

// ExpiresInDaysNotNil applies the NotNil predicate on the "expires_in_days" field.
func ExpiresInDaysNotNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotNull(FieldExpiresInDays))
}

// ManualURLEQ applies the EQ predicate on the "manual_url" field.
func ManualURLEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldManualURL, v))
}

// ManualURLNEQ applies the NEQ predicate on the "manual_url" field.
func ManualURLNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldManualURL, v))
}

// ManualURLIn applies the In predicate on the "manual_url" field.
func ManualURLIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldManualURL, vs...))
}

// ManualURLNotIn applies the NotIn predicate on the "manual_url" field.
func ManualURLNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldManualURL, vs...))
}

// ManualURLGT applies the GT predicate on the "manual_url" field.
func ManualURLGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldManualURL, v))
}

// ManualURLGTE applies the GTE predicate on the "manual_url" field.
func ManualURLGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldManualURL, v))
}

// ManualURLLT applies the LT predicate on the "manual_url" field.
func ManualURLLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldManualURL, v))
}

// ManualURLLTE applies the LTE predicate on the "manual_url" field.
func ManualURLLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldManualURL, v))
}

// ManualURLContains applies the Contains predicate on the "manual_url" field.
func ManualURLContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldManualURL, v))
}

// ManualURLHasPrefix applies the HasPrefix predicate on the "manual_url" field.
func ManualURLHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldManualURL, v))
}

// ManualURLHasSuffix applies the HasSuffix predicate on the "manual_url" field.
func ManualURLHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldManualURL, v))
}

// ManualURLIsNil applies the IsNil predicate on the "manual_url" field.
func ManualURLIsNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIsNull(FieldManualURL))
}

// ManualURLNotNil applies the NotNil predicate on the "manual_url" field.
func ManualURLNotNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotNull(FieldManualURL))
}

// ManualURLEqualFold applies the EqualFold predicate on the "manual_url" field.
func ManualURLEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldManualURL, v))
}

// ManualURLContainsFold applies the ContainsFold predicate on the "manual_url" field.
func ManualURLContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldManualURL, v))
}

// DeliveryTemplateEQ applies the EQ predicate on the "delivery_template" field.
func DeliveryTemplateEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldDeliveryTemplate, v))
}

// DeliveryTemplateNEQ applies the NEQ predicate on the "delivery_template" field.
func DeliveryTemplateNEQ(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldDeliveryTemplate, v))
}

// DeliveryTemplateIn applies the In predicate on the "delivery_template" field.
func DeliveryTemplateIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldDeliveryTemplate, vs...))
}

// DeliveryTemplateNotIn applies the NotIn predicate on the "delivery_template" field.
func DeliveryTemplateNotIn(vs ...string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldDeliveryTemplate, vs...))
}

// DeliveryTemplateGT applies the GT predicate on the "delivery_template" field.
func DeliveryTemplateGT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldDeliveryTemplate, v))
}

// DeliveryTemplateGTE applies the GTE predicate on the "delivery_template" field.
func DeliveryTemplateGTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldDeliveryTemplate, v))
}

// DeliveryTemplateLT applies the LT predicate on the "delivery_template" field.
func DeliveryTemplateLT(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldDeliveryTemplate, v))
}

// DeliveryTemplateLTE applies the LTE predicate on the "delivery_template" field.
func DeliveryTemplateLTE(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldDeliveryTemplate, v))
}

// DeliveryTemplateContains applies the Contains predicate on the "delivery_template" field.
func DeliveryTemplateContains(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContains(FieldDeliveryTemplate, v))
}

// DeliveryTemplateHasPrefix applies the HasPrefix predicate on the "delivery_template" field.
func DeliveryTemplateHasPrefix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasPrefix(FieldDeliveryTemplate, v))
}

// DeliveryTemplateHasSuffix applies the HasSuffix predicate on the "delivery_template" field.
func DeliveryTemplateHasSuffix(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldHasSuffix(FieldDeliveryTemplate, v))
}

// DeliveryTemplateIsNil applies the IsNil predicate on the "delivery_template" field.
func DeliveryTemplateIsNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIsNull(FieldDeliveryTemplate))
}

// DeliveryTemplateNotNil applies the NotNil predicate on the "delivery_template" field.
func DeliveryTemplateNotNil() predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotNull(FieldDeliveryTemplate))
}

// DeliveryTemplateEqualFold applies the EqualFold predicate on the "delivery_template" field.
func DeliveryTemplateEqualFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEqualFold(FieldDeliveryTemplate, v))
}

// DeliveryTemplateContainsFold applies the ContainsFold predicate on the "delivery_template" field.
func DeliveryTemplateContainsFold(v string) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldContainsFold(FieldDeliveryTemplate, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalFulfillmentSKU) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalFulfillmentSKU) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalFulfillmentSKU) predicate.ExternalFulfillmentSKU {
	return predicate.ExternalFulfillmentSKU(sql.NotPredicates(p))
}
